### ISSUE TITLE
indexing/formatting changes

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#10]
1. We are now using `@unit` instead of `@n` in `<biblScope>` should make sure to index that
1. You are currently indexing the content of  `<settlement>`, which is picking up the `<geo>` element that is inside some of them. See Place list on production search page. It's getting all text content.
1. Would it be possible to either ignore the `--` that are in front of some genres, and index on first alphabetic char? or strip completely

**Comment by emylonas** [comment]
The markup for `<settlement>` is: 
```
<settlement ref="http://pleiades.stoa.org/places/"> <geo>[lat,long]</geo></settlement>
```

I added `--` in front of some taxonomy labels to indicate to encoders that these are belong to a set. It's helpful in Oxygen, but problematic in the display!

**Comment by crotger** [comment]
closing as item 1 and 2 are handled, and we decided not to put `--` in the inscriptions after all.
