### ISSUE TITLE
letter measurement is in object section

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#102]
```
beth0077.xml: <width>letters 12</width>
beth0143.xml: <width>letters 4</width>
beth0239.xml: <width>letters 5</width>
```

**Comment by emylonas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change dimension display to have cm following measurement. clarify "let." (remove if letter dimensions aren't there)](https://trello.com/c/icElG9wm/60-change-dimension-display-to-have-cm-following-measurement-clarify-let-remove-if-letter-dimensions-arent-there)

**Comment by GaiaLembi** [comment]
@emylonas 
Beth0143: done
For Beth0077 and 0239 I will need to check the publications as they are not available on line

**Comment by GaiaLembi** [comment]
All done, although the whole Beth Shearim series is kind of a mess... will open a specific issue for that
