### ISSUE TITLE
Dimensions of fragments and variable size

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#103]
Should we do the fragments in the same way? 
Also, I'm not sure whether the both sena measurements are trying to show the same kind of information (variable height) or if sena0005 is talking about 2 fragments. 

```
sena0002.xml: <height>22 to 24</height>
sena0005.xml: <width>10 and 46</width>

mger0074.xml: <depth>A: 11.3, B: 11.0</depth>
mger0074.xml: <height>A: 22.0, B: 22.0</height>
mger0074.xml: <width>A: 8.0, B: 12.0</width>
mger0388.xml: <depth>Fragment A: 20.0, fragment B: 10.0</depth>
mger0388.xml: <height>fragment A: 40.0, fragment B: 28.5</height>
mger0388.xml: <width>fragment A: 34.5, fragment B: 33.5</width>
```

**Comment by emylonas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change dimension display to have cm following measurement. clarify "let." (remove if letter dimensions aren't there)](https://trello.com/c/icElG9wm/60-change-dimension-display-to-have-cm-following-measurement-clarify-let-remove-if-letter-dimensions-arent-there)

**Comment by GaiaLembi** [comment]
@emylonas 
sena0002: "The dimensions of fragments A and B are 22 cm high by 33 cm wide and 24 cm high by 50 cm wide, respectively" -- that is why we have 22 to 24 (which I deem correct in form) and a total of 83 cm for the width
sena0005: "The left fragment is 10 cm wide while the right is 46 cm": the "and" is therefore correct, as the measures refer to different fragments.
mger0074 and 0388 seem fine to me: have you corrected them?
ISSUE CAN BE CLOSED ON MY PART

**Comment by emylonas** [comment]
all set by me.
