### ISSUE TITLE
Insert "flagstone" in Type of Object list?

### ISSUE THREAD

**Issue by GaiaLembi** [Brown-University-Library/iip-texts#113]
Most hammxxxx labeled as such by the editor. Slab was used in most cases in our corpus

**Comment by emylonas** [comment]
Added to classifications, but we don't have a Getty AAT number - 300011687 is "flagstone" but it's seems to want to determine the type of stone as well as the architectural function. Says it's slate or bluestone.

**Comment by emylonas** [comment]
inserted. closing
