### ISSUE TITLE
validation errors: various

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#12]
idum0219: `<supportDesc ana="">`  value for `@ana`

 `<condition ana="">`  value for `@ana` or delete entirely
idum0222 
masa0466
masa0480
masa0611
masa0693
masa0695

Value of attribute "reason" is invalid; must be equal to "ellipsis", "illegible", "lost" or "omitted"
idum0004.xml  (3x)

Value of attribute "reason" is invalid; must be equal to "explanation", "lost", "omitted", "subaudible" or "undefined"
masa0038.xml  
masa0554.xml (3x)

**Comment by GaiaLembi** [comment]
Done.
There is, however, a huge issue with masa0038, in that the name the file was saved with doesn't correspond to the actual ID in the xml. I will redo it altogether
