### ISSUE TITLE
subaudible

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#125]
Is this another way of handling alternate spellings? see #123 ? 

ex: ashk0002, zoor0407, zoor0412 , jaff0028

if these are ok, how should we indicate the subaudible characters ? in the Guidelines, it says to use (scil. xxx) https://www.stoa.org/epidoc/gl/latest/trans-subaudible.html

**Comment by emylonas** [comment]
These have subaudible as reason in supplied:

```
(6) ashk0002.xml: <lb break="no"/> εγκα ὑπὲρ σωτερ<supplied reason="subaudible">ίας</supplied>
(3) ashk0003a.xml: </expan>, <supplied reason="subaudible">divi</supplied> Severi
idum0026.xml: <lb/>קוסינקם <supplied reason="subaudible">מן בני בעלרים</supplied>
jaff0028.xml: τοῦ γένους<lb/>αὐτῶν κὲ ἀδελφῆς<lb/>αὐτῶν Κοχχαθιων<lb/>πέντε <foreign xml:lang="heb">שלו<supplied reason="subaudible">ם</supplied>
jaff0052.xml: <lb/>הקבר הזה שלרב<lb/>יודן הכ<supplied reason="subaudible">ה</supplied>ן ברב<lb/>נוח נפש שמן לוד<lb/>
```

**Comment by GaiaLembi** [comment]
@emylonas 
I am a bit at loss with these. 
In the guidelines subaudible is defined as such: "Editorial supplement of words subaudible to the native reader", which may fit our inscription. What confuses me, though, is the display, which has a _scil._ In the printed texts there are usually round parentheses

**Comment by emylonas** [comment]
change display so that supplied `<reason="subaudible">` has parentheses.

**Comment by emylonas** [comment]
made change, check ashk0002 after next commit

**Comment by emylonas** [comment]
seems to work. closing
