### ISSUE TITLE
Validation Error: Date

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#13]
The following files have no value in the `@notBefore` and `@notAfter` fields:

- idum0002.xml
- idum0005.xml
- idum0009.xml
- idum0010.xml
- idum0024a.xml
- idum0027.xml
- idum0031.xml
- idum0038.xml
- idum0039.xml
- idum0040.xml
- idum0041.xml
- idum0043.xml
- idum0044.xml
- idum0045.xml
- idum0046.xml
- idum0047.xml
- idum0048.xml
- idum0049.xml
- idum0050.xml
- idum0051.xml
- idum0052.xml
- idum0053.xml
- idum0054.xml
- idum0055.xml

**Comment by GaiaLembi** [comment]
Done
