### ISSUE TITLE
check to see if these inscriptions should have text content

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#134]
masa0427
masa0428
masa 0682

idum0296
idum0304

**Comment by GaiaLembi** [comment]
masa0427
masa0428
masa 0682
Can be cancelled: the notes are in the publication itself, but there is no transcription whatsoever and I cannot gather enough from the pictures to provide one

**Comment by emylonas** [comment]
done with commit 2aba1d41a
