### ISSUE TITLE
Bibliographic Entry is missing page or inscription number

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#139]
```
alji0001.xml: Every entry must include bibliography, even if it is unpublished
alji0002.xml: Every entry must include bibliography, even if it is unpublished
beth0087.xml: Every entry must include bibliography, even if it is unpublished
beth0120.xml: Every entry must include bibliography, even if it is unpublished
caes0155.xml: Every entry must include bibliography, even if it is unpublished
caes0178.xml: Every entry must include bibliography, even if it is unpublished
caes0228.xml: Every entry must include bibliography, even if it is unpublished
caes0389.xml: Every entry must include bibliography, even if it is unpublished
elme0001.xml: Every entry must include bibliography, even if it is unpublished
elme0002.xml: Every entry must include bibliography, even if it is unpublished
jord0001.xml: Every entry must include bibliography, even if it is unpublished
qast0001.xml: Every entry must include bibliography, even if it is unpublished
```

**Comment by GaiaLembi** [comment]
All done except the following (couldn't find journal on line):
elme0001.xml: Every entry must include bibliography, even if it is unpublished
elme0002.xml: Every entry must include bibliography, even if it is unpublished
Jord0001 and Qast0001 are a mess encoding wise, although for different reason: the first was transcribed, I suspect, from the photograph itself (no transcription in the referenced publication; the second present a problem with the script, which should be Syro-Palestinian (i.e. Syriac letters), and not Hebrew

**Comment by GaiaLembi** [comment]
For elme0001 and 0002
Conical Sundial and Ikon Inscription from the Kastellion Monastery on Khirbet el-Merd in the Wilderness of Judah
Journal of the Palestine Oriental Society 9 (1929) Issue 3-4

**Comment by zeichman** [comment]
I got access to a digital copy and have completed the bibliography for the last of these, as well as updated the reference within the xml files.
