### ISSUE TITLE
Jord0001 Qast0001 errors in encoding

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#140]
Jord0001 and Qast0001 are a mess encoding wise, although for different reasons: the first was transcribed, I suspect, from the photograph itself (no transcription in the referenced publication); the second presents a problem with the script, which should be Syro-Palestinian (i.e. Syriac letters), and not Hebrew

Jord0001 need to look for more recent bibliography or edition

qast0001 should be in Syriac script. need to get it typed in.

**Comment by mlsatlow** [comment]
See: https://en.wikipedia.org/wiki/Gabriel%27s_Revelation for info on Jord0001 - there is perhaps a better edition.
Gaia, can you take care of both of these things?

**Comment by emylonas** [comment]
jord0001 redone by Gaia, that one is all set.

**Comment by zeichman** [comment]
I've been in contact with a Syriac expert who has clarified to me a few things about qast0001
1) The inscription does not in fact use Syriac letters, but Christian Palestinian Aramaic, which is similar but unique.
2) There are no Unicode fonts that actually display CPA or Syriac. When he transcribed it for me (using both CPA and Syriac characters), he had to download a font for CPA and use the standard scholarly font for Syriac.

Given that the inscription is in fact Aramaic, I think we can close this. I have done further corrections to the Greek inscription which I am committing.

**Comment by zeichman** [comment]
Waffling on this - my apologies. It is indeed Syriac and it has been changed to such in both the transcription and the iso code.
