### ISSUE TITLE
questions around <unclear/>

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#141]
**unlear elements together with gaps**
caes0074 l. 122ff
 There is a `<gap reason="illegible" unit="character" quantity="4"/>` followed by 4 `<unclear/>` elements followed by another `<gap reason="illegible" unit="character" quantity="3"/>` 

Is this just a single gap of 11 characters? Or is there a significance to the subdivisions of gaps? 

there are others like this,   for ex. caes0212 l. 134ff
caes0348 l. 133
caes0362 l. 136ff
case0388 l. 130ff
elus0009 l. 144ff

**individual unclear letters should be one single unclear?** 
caes0156 l. 134ff - each letter is wrapped in an `<unclear>` element. Shouldn't they all be in a single `<unclear>ΔΙΑΑΛΣ</unclear>` ?

**Comment by GaiaLembi** [comment]
@emylonas 
All done
As for unclear letters: correct, single unclear if there are multiple in a row
