### ISSUE TITLE
Diplomatic and Transcription mixups

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#144]
**These inscriptions have many capital letters in the "transcription" div. In some cases, these should be marked as `<orig>` but are not.** 
```
beth0073.xml: <p>ΑΒΓΔΕΖΗΘ Ι </p>
beth0166.xml: <p>ΑΑΛ<lb/>Ν<cb/>Κυρὰ Μικκή<lb/>ΑΝΥΑ ΑΘΙΣ </p>
beth0231.xml: <lb/> ΡΑΒΙ ΓΑΜΑΛΙΗΛ </p>
caes0156.xml: <p>ΤΙΣ ΤΗΝ ΚΟΡΗΝ ΦΙΛΑΤΟ ΗΝ ΕΝΔ<gap reason="illegible" quantity="3" unit="character"/>ΤΙΣ <unclear/>ΟΙΟ<unclear/>
elus0001.xml: <p>ΛΟ ΒΗ</p>
elus0019.xml: <p>Ι Ω <lb/>Ε Σ</p>
elus0028.xml: <unclear/>Ι Β<unclear>ΙΙ</unclear> +</p>
elus0033.xml: <lb/>Σ Α</p>
elus0050.xml: <lb/>ΝΑ Σ</p>
elus0056.xml: <lb/>ΛΙ ΜΙΣ</p>
elus0060.xml: <p>Ι Ω<gap reason="illegible" unit="character" extent="unknown"/>
elus0063.xml: <unclear/>ΚΕ ΒΕ<unclear/>
elus0073.xml: <p>Μ Α</p>
elus0074.xml: <p>Α Λ<lb/>
elus0105.xml: <p>ΕΡ Ω<unclear>Ν</unclear>
sena0006.xml: <gap reason="illegible" unit="character" extent="unknown"/>ΟΥ Ο ΕΙ<unclear>Σ</unclear>
masa0382.xml: <p>IICB T<unclear>P</unclear>
sina0114.xml: <p>WDD LHLMT MḤṢT</p>
```
It looks as if mare0309 has the transcription in the diplomatic div.
There are about 550 inscriptions with lower case letters in the diplomatic div. Most of them are more or less diplomatic - they use spaces, and many have transcription divs as well. Hard to sort them out. 

I'm not sure that looking for transcriptions without diplomatic and _vice versa_ will help.

**Comment by emylonas** [comment]
There are two inscriptions with a diplomatic div that have no transcription div and there is a lower case letter: 
```
caes0016 <unclear>Υ</unclear>βΟ</p>
caes0072. ΣβΩ<lb/>
fiqg0002  is a complete inscription, could be diplomatic or edited 
```

These also have `<gap reason="illegible" quantity="3" unit="character"/>` at the beginning of the line, which makes me think it's supposed to be an `extent="unknown"` gap instead.

**Comment by GaiaLembi** [comment]
The one you singled out stand corrected
