### ISSUE TITLE
Inscriptions to be checked

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#151]
caes0430 measures and object type seem off. and only has a few letters
caes0435 same
caes0440 missing bib ref
caes0441 first line seems wrong. There is no text (and empty unclear element) in 1st line, and transcription shows ΙΣ ΧΣ. And should be abbrev. not supplied.
caes0421 diplomatic and edited don't match.
caes0442 discrepancy between diplomatic and edited, no condition metadata
caes0638 single letter no date, bib not ok?
caes0639 single letter no date, bib not ok?
caes0635, caes0636, caes0637 bib not clear if page or inscription number (probably page)

**Comment by emylonas** [comment]
yotv0001 there is something that looks like an erasure that is marked as `<supplied reason="lost">` Should check to see if it's marked correctly.

**Comment by zeichman** [comment]
Hi Elli, 

I have fixed yodv0001, but I don't see the various caes files either in GitHub or on the website - none of them, in fact. Where are you seeing them?

**Comment by emylonas** [comment]
This list of files refers to the old student files in the folder `IIP Files > old student files > Not Finished` and seems to be a list of what was wrong with each file. The folder has all the files mentioned above and two more: caes0636 caes0637 and idum0628. Mystery solved!

**Comment by zeichman** [comment]
corrected and included caes 0421, 0430, 0435, 0440, 0441, 0442. Deleted 0635-9 and idum0628 as there was little usable information in here.

Closing the issue.
