### ISSUE TITLE
IIP Location in Archive number showing after book titles

### ISSUE THREAD

**Issue by zeichman** [Brown-University-Library/iip-texts#153]
The Zotero "Location in Archive" number shows in IIP entries immediately after the title of the book in the bibliography. This, from what I can tell, only seems to be for Zotero entries listed as "Book section". See https://library.brown.edu/iip/viewinscr/caes0434/ or https://library.brown.edu/iip/viewinscr/akld0007/

**Comment by zeichman** [comment]
This seems to apply to Zotero entries marked as "book" as well: https://library.brown.edu/iip/viewinscr/jeri0019/

**Comment by emylonas** [comment]
This is an issue that is also opened in the production repository - https://github.com/Brown-University-Library/iip-production/issues/41  and has to be fixed in the django code that handles Zotero.

**Comment by emylonas** [comment]
closed in production repository. Any remaining strange displays may be citation types in Zotero
