### ISSUE TITLE
Files with incomplete <gap> elements

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#156]
There are 6 files where gaps are encoded as `<gap reason="lost"/>`, but they should be either
`<gap reason="lost" unit="chars" extent="unknown"/> or some other indication of unit and count of characters/lines They won't format properly otherwise. 

caes0442
mare0506
mtab0001 (9 elements)
susi0007 (2 elements)
tbye0002
tbye0003

**Comment by zeichman** [comment]
Fixed all these files!
