### ISSUE TITLE
some questions that came up as I was converting <supplied> elements (2)

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#157]
jeru

- jeru0064 l. 127 there is an `unclear` inside a `supplied`. This doesn't make sense. Should it be just `supplied` or just `unclear`? 
- beth0212, beth0213, caes0004, caes0211, kafr0100, caes0211 have "or" to indicate two possible conjectures. I think we mark this as `<choice><unclear>xx</unclear><unclear>yy</unclear></choice>`
- caes0534, mare0426, mare0191 should these be tagged as `<orig>` The text doesn't seem to be meaningful. 
- mare0247 the expan is incomplete. 
- caes0109 is the `<space>` a vertical gap? 
- There are some cases where the drachma mark is either tagged as an `<am>` outside an `<expan>` or not tagged at all. (

**Comment by emylonas** [comment]
caes0338 I think the name should be Γρηγορίου, not Γρηγπριου. 
giva0001 is all supplied. Is that right? the translation looks different. 
zoor0216 l. 153-4 there is a `sic/corr` because there is a symbol `+` inside a word. This isn't a spelling error.

**Comment by zeichman** [comment]
I went through most of these. I found the editio princeps for some, which were more certain in their reconstruction of supplements than the files indicate. giva0001 is correct - there's only a few words that are not supplied

I could not find caes0534 in our files, though. Is that the name of it?

Caes0109 is a vertical gap - not sure how to encode columns in a way that displays things in an intelligible way.

**Comment by emylonas** [comment]
sena0001 l. 130 question mark
sena0003 l. 129 question mark
hamm0013 l 158 question mark
sepp0023 l. 132 question mark
caes0144 ellipsis - probably a gap. l. 132, l. 134
zoor0221 l. 154 has a choice for the word `indiction`, then supplies it in the following line.

**Comment by emylonas** [comment]
rafi0008 has an `<unclear>` inside a `<supplied>` which makes no sense.

**Comment by emylonas** [comment]
@zeichman here's another odd one. caes0172. The transcription doesn't make much sense and I can't tell if it's someone who doesn't speak Greek writing the inscription or whether the transcriber wasn't very good with Greek. You could fix the `<lb break="no"/>` when you look at it.

**Comment by emylonas** [comment]
@zeichman ashk0002 also looks as if it either has mis-spellings or the orig/regs aren't marked. I think.
