### ISSUE TITLE
supportDesc/support/dimensions/width

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#16]
Going through old notes: I have found a number of files (1424) that have the width and other dimensions in supportDesc written as follows:

```
<dimensions type="surface">
      <height unit="m" quantity="1"/>
      <width unit="m" quantity="1"/>
      <depth>unknown</depth>
</dimensions>
```

Our current template and recent files use the following format:

```
<dimensions type="surface" unit="cm">
       <height>52</height>
       <width>24</width>
      <depth>29</depth>
</dimensions>
```

Double checking that I should make everything look like the 2nd example, and have the unit of measurement as an attribute of `<dimensions>` Is that right? 
@crotger what do we index? 

Also - they use different dimensions...

**Comment by GaiaLembi** [comment]
Correct, everything should look like the second example.
Unit should be centimeters
Gaia

**Comment by emylonas** [comment]
So far, have changed the contained height, width and depth elements to a) have the quantity value as content of the element. b) to mostly be cm

**Comment by emylonas** [comment]
No  more "m" units in Support. we do have atLeast and atMost, and not all the quantities are changed to content yet.

**Comment by emylonas** [comment]
Should be finished except for problematic files listed in #28, #29, perhaps some others.

**Comment by emylonas** [comment]
close with 0ec9c50
