### ISSUE TITLE
more possible content corrections

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#160]
bett0001 l. 130: should it be `ἀντιλή<supplied reason="lost">μ</supplied>φεως` or some other spelling. I know it comes from αντιλαμβάνω, but the spelling is strange, αντιλήψεως? strange.

khsh0003, khis0081, einf0001 all have multiple words in the `<ex>` part of the `<expan>` - shouldn't these be subaudible or supplied, outside the abbreviation? 

gaza0111 l. 144: should it be `<supplied reason="lost">ἐ</supplied>φήφωσεν` or corrected to `<supplied reason="lost">ἐ</supplied>ψήφωσεν`

jeri0019 l. 131, 132: very strange use of the `<expan>` etc. (2 times)

zoor0261 l. 151: `<lb/>ἐν μηνὶ <expan><abbr>Ξαν<lb break="no"/>θ,<am>ϛ</am></abbr><ex>ικῷ</ex></expan>` I'm not sure what the `,<am>ϛ</am>` is. the stigma could be an abbreviation mark, but what about the comma?

**Comment by zeichman** [comment]
fixed all on the list
