### ISSUE TITLE
Possible cause of 500 errors

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#162]
we have 16 files, recently added by Nesya, which are in the IIP archival format. This format seems to have been introduced recently, in the last commit. You can see the difference if you look at them, especially the taxonomy section, where the taxonomy values are explicitly added to the file.  There may be more files with 500 errors, but these 16 definitely seem to have a problem. 
```
epidoc-files/akld0019.xml
epidoc-files/beth0245.xml
epidoc-files/einn0002.xml
epidoc-files/idum0160.xml
epidoc-files/jaff0018.xml
epidoc-files/jaff0021.xml
epidoc-files/jaff0057.xml
epidoc-files/jeru0342.xml
epidoc-files/masa0429.xml
epidoc-files/masa0430.xml
epidoc-files/masa0435.xml
epidoc-files/masa0454.xml
epidoc-files/masa0468.xml
epidoc-files/masa0469.xml
epidoc-files/masa0525.xml
epidoc-files/masa0527.xml
```

I have been checking other files, and am not finding 500 errors. If you find any, please append to this thread. These files are encoded incorrectly. Did Nesya by mistake go into the archival directory? Confusing.

**Comment by zeichman** [comment]
I'm not sure how this happened - I definitely noticed when I was committing the files that there were changes to the header, but I assumed it was the opposite (i.e., an automated update). I will keep an eye open for this in the future and post any additional examples I come across.

**Comment by zeichman** [comment]
I've gone through all the files Nesya has recently edited and the only additional 500 error seems to be for mger0152.xml

**Comment by emylonas** [comment]
Some time between April 20, 2020 and April 20, 2021, 17 files were changed in our epidoc files directory, and replaced with the version that was in the archival files. The archival format is not compatible with process we use to index files when they are committed to GitHub, so it's causing errors. Most of the changes have been fixed by Chris, but mger0152 wasn't in the list above. Also, we should perhaps diff these 17 files, to make sure that all changes were applied to the correct version.

**Comment by emylonas** [comment]
mger0152 is working. the other files are still in the old format. Will produce a better list.

**Comment by zeichman** [comment]
Awesome - I'd be happy to re-encode them individually. It shouldn't take too long to do, if you think that's the best way to go about it.

**Comment by zeichman** [comment]
Revised list:
'''epidoc-files/akld0019.xml
epidoc-files/beth0245.xml
epidoc-files/einn0002.xml
epidoc-files/idum0005.xml
epidoc-files/idum0052.xml
epidoc-files/idum0160.xml
epidoc-files/idum0306.xml
epidoc-files/jaff0018.xml
epidoc-files/jaff0021.xml
epidoc-files/jaff0057.xml
epidoc-files/jeru0342.xml
epidoc-files/jeru0383.xml
epidoc-files/jeru0390.xml
epidoc-files/jeru0391.xml
epidoc-files/masa0387.xml
epidoc-files/masa0388.xml
epidoc-files/masa0429.xml
epidoc-files/masa0430.xml
epidoc-files/masa0435.xml
epidoc-files/masa0454.xml
epidoc-files/masa0468.xml
epidoc-files/masa0469.xml
epidoc-files/masa0525.xml
epidoc-files/masa0527.xml'''

**Comment by zeichman** [comment]
All are completely fixed! Huzzah!
