### ISSUE TITLE
Errors to correct for word breaking. Also oddities

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#164]
masa0595: a number is tagged as `<orig>` probably should be `<num>`. If it's in caps, then it can be typed in caps. but the comment implies that it's understood as a number

ashd0004 there is a `<gap>` in the `<supplied>` as well as space between `><` 
other inscription with `<gap>` inside `<supplied>`
  jeru0342, yavn0004 (4x), mare0188

There are 45 files with 130 cases of spaces inside a RTL foreign element. some are spaces at the beginning or end of the element, some are cases of multiple words, which should each be enclosed in it's own `<foreign>` element. Also, no numbers or `<g>` elements inside `<foreign>`,  especially if they are figures. apol0002.xml
beth0028.xml (2x)
beth0029.xml (5x)
beth0041.xml (3x)
beth0049.xml (2x)
beth0069.xml (2x)
beth0079.xml (4x)
beth0117.xml (2x)
beth0119.xml (2x)
beth0179.xml (2x)
beth0204.xml (2x)
beth0220.xml (2x)
caes0180.xml (2x)
caes0181.xml (3x)
caes0183.xml (5x)
jaff0012.xml (2x)
jaff0024.xml (2x)
jaff0026.xml (2x)
jaff0028.xml
jaff0033.xml
jaff0079.xml
jaff0083.xml
jeri0013.xml (5x)
jeri0015.xml (6x)
jeru0016.xml (2x)
jeru0022.xml (2x)
jeru0053.xml (4x)
jeru0080.xml (4x)
jeru0101.xml (5x)
jeru0171.xml (2x)
jeru0172.xml
jeru0311.xml (2x)
jeru0411.xml (3x)
jeru0552.xml
khzi0001.xml (6x)
masa0941.xml (8x)
qast0001.xml (3x)
sepp0018.xml (4x)
sepp0019.xml (3x)
sepp0020.xml (3x)
sepp0021.xml (6x)
shap0002.xml (2x)
shap0003.xml (2x)
tdor0003.xml (2x)
zoor0409.xml (5x)

zoor0080 incorrect choice element l. 166
zoor0296 l. 129 - the `<sic>` element has a second word that doesn't appear in the `<corr>` element. Τιμετ<unclear>ῆ</unclear>ος . Either we should add it to the corr, or perhaps is goes after the `<choice>`?

**Comment by zeichman** [comment]
Closing. New issue created - #170 lists all ````<foreign>```` tags that include more than one word with a directional difference from the main language. 

All other files have been fixed in most recent commit listed in this issue.
