### ISSUE TITLE
Errors to correct for word breaking: gap inside del

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#166]
caes0004.xml (x2)
caes0008.xml (x10)
caes0013.xml (x2)
caes0015.xml
caes0016.xml (x2)
mare0409.xml
zoor0446.xml

**Comment by zeichman** [comment]
I'm not sure I understand how best to approach this. My impression was that the ````<del>```` tag did not indicate anything inherent about the actual readability/visibility of the letters on the inscription. My impression was that it spoke to an intent of erasure at some point. Characters might or might not be visible within the ````<del>```` tag - the tag itself doesn't indicate either way, right? Hence, supplieds, gaps, unclears, and origs would seem par for course within ````<del>````. Or am I misunderstanding?

**Comment by emylonas** [comment]
yes, you are right about the purpose of `<del>` 
I am sometimes confused by the fact that the text is erased, but it's also a gap. In other words, how do we know it's erased? and also the feeling that all text inside a del would be supplied. I know that there are partial erasures and formulae so you can tell what it should have said. It's a bit confusing, however. and without the print edition. Also, these are all Caesarea, which I mistrust. If  the markup looks legit to you, that's fine.
