### ISSUE TITLE
jaffa0081 mystery tag

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#167]
jaffa0081 has the following at the very end:
`<lb/><term xml:id="seq1" xml:lang="heb">לֹעזר</term></p>`

the `<term>` element is copied with its xml:id into the segmented div, and that causes 2 identical xml:id attributes in one file, which is invalid XML. I think we should probably eliminate the element completely. Or at least the attribute. Not sure what it's doing there, but it's the only one in the whole corpus.

**Comment by zeichman** [comment]
changed to foreign tag
