### ISSUE TITLE
/TEI/teihandDesc/handNote/dimensions/height

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#18]
old files (935) have 
```
<handNote ana="#painted">
  <dimensions type="letter">
   <height unit="cm" atLeast="5" atMost="14"/>
   </dimensions>
</handNote>
```

new files and template have:
```
<handNote ana="">
  <dimensions type="letter" extent="height" unit="cm" atLeast=""atMost=""/>
   <p></p>
</handNote>
```

Again, I can fix these to all look like the 2nd example but am checking before hand.

**Comment by emylonas** [comment]
Also, 312 files have this: 
```
<handNote ana="#engraved">
     <dimensions type="letter">
    <height><?not-yet-handling @exact=3 @unit=cm 3 cm?></height>
    </dimensions>
</handNote>
```

I think I can fix most of these automatically, so they match this format
`<dimensions type="letter" extent="height" unit="cm" atLeast="" atMost=""/>`
The ones with the 0 values we can eliminate. if I run into difficulties, I'll note them. But waiting for an ok.

ahma0003.xml  <height><?not-yet-handling @exact=3 @unit=cm 3 cm?></height>
akas0001.xml  <height><?not-yet-handling @exact=8 @unit=cm 8 cm?></height>
akas0002.xml  <height><?not-yet-handling @exact=5 @unit=cm 5 cm?></height>
anna0001.xml  <height><?not-yet-handling @exact=18 @unit=mm 18 mm?></height>
anna0003.xml  <height><?not-yet-handling @exact=2 @unit=cm 2 cm?></height>
anna0004.xml  <height><?not-yet-handling unknown?></height>
baid0001.xml  <height><?not-yet-handling @exact=8 @unit=cm 8 cm?></height>
beth0009.xml  <height><?not-yet-handling 6 cm?></height>
beth0012.xml  <height><?not-yet-handling 5 cm?></height>
beth0047.xml  <height><?not-yet-handling 6 cm?></height>
beth0064.xml  <height><?not-yet-handling 5 cm?></height>
beth0068.xml  <height><?not-yet-handling 3 cm?></height>
beth0084.xml  <height><?not-yet-handling 6 cm?></height>
beth0131.xml  <height><?not-yet-handling 15 mm?></height>
beth0144.xml  <height><?not-yet-handling 5 cm?></height>
beth0179.xml  <?not-yet-handling 3.5 cm?>
beth0201.xml  <?not-yet-handling 3 cm?>
beth0210.xml  <height><?not-yet-handling 4 cm?></height>
beth0211.xml  <height><?not-yet-handling 3 cm?></height>
beth0214.xml  <height><?not-yet-handling 25 mm?></height>
beth0216.xml  <height><?not-yet-handling 3 cm?></height>
beth0218.xml  <height><?not-yet-handling 2 cm?></height>
beth0223.xml  <height><?not-yet-handling 2.5 cm?></height>
beth0233.xml  <height><?not-yet-handling 4 cm?></height>
beth0237.xml  <height><?not-yet-handling 4 cm?></height>
beth0244.xml  <height><?not-yet-handling 2 cm?></height>
beth0249.xml  <height><?not-yet-handling 4 cm?></height>
caes0023.xml  <height><?not-yet-handling @exact=65 @unit=mm 65 mm?></height>
caes0029.xml  <height><?not-yet-handling @exact=60 @unit=mm 60 mm?></height>
caes0034.xml  <height><?not-yet-handling @exact=24 @unit=mm 24 mm?></height>
caes0036.xml  <height><?not-yet-handling @exact=45 @unit=mm 45 mm?></height>
caes0056.xml  <height><?not-yet-handling @exact=0.11 @unit=m 0.11 m?></height>
caes0060.xml  <height><?not-yet-handling @exact=0.11 @unit=m 0.11 m?></height>
caes0061.xml  <height><?not-yet-handling @exact=0.11 @unit=m 0.11 m?></height>
caes0064.xml  <height><?not-yet-handling @exact=80 @unit=mm 80 mm?></height>
caes0065.xml  <height><?not-yet-handling @exact=50 @unit=mm 50 mm?></height>
caes0066.xml  <height><?not-yet-handling @exact=35 @unit=mm 35 mm?></height>
caes0067.xml  <height><?not-yet-handling @exact=52 @unit=mm 52 mm?></height>
caes0068.xml  <height><?not-yet-handling @exact=35 @unit=mm 35 mm?></height>
caes0083.xml  <height><?not-yet-handling @min=27 @max=43 @unit=mm 27-43?></height>
caes0118.xml  <height><?not-yet-handling @exact=29 @unit=mm 29 mm?></height>
caes0125.xml  <height><?not-yet-handling @exact=55 @unit=mm 55 mm?></height>
caes0127.xml  <height><?not-yet-handling @exact=21 @unit=mm 21 mm?></height>
caes0139.xml  <height><?not-yet-handling @exact=20 @unit=mm 20 mm?></height>
caes0172.xml  <height><?not-yet-handling @exact=20 @unit=mm 20 mm?></height>
caes0177.xml  <height><?not-yet-handling @min=15 @max=26 @unit=mm mm?></height>
caes0187.xml  <height><?not-yet-handling @exact=35 @unit=mm 35 mm?></height>
caes0188.xml  <height><?not-yet-handling @exact=25 @unit=mm 25 mm?></height>
caes0195.xml  <height><?not-yet-handling Unknown?></height>
caes0196.xml  <height><?not-yet-handling @exact=5 @unit=mm 5 mm?></height>
caes0203.xml  <height><?not-yet-handling @exact=25 @unit=mm 25 mm?></height>
caes0206.xml  <height><?not-yet-handling @exact=40 @unit=mm 40 mm?></height>
caes0215.xml  <height><?not-yet-handling @min=30 @max=60 @unit=mm ca. 30-ca. 60 mm?></height>
caes0217.xml  <height><?not-yet-handling @exact=32 @unit=mm 32 mm?></height>
caes0219.xml  <height><?not-yet-handling @exact=38 @unit=mm 38 mm?></height>
caes0220.xml  <height><?not-yet-handling @exact=47 @unit=mm 47 mm?></height>
caes0222.xml  <height><?not-yet-handling @exact=38 @unit=mm 38 mm?></height>
caes0225.xml  <height><?not-yet-handling @exact=44 @unit=mm 44 mm?></height>
caes0226.xml  <height><?not-yet-handling @exact=26 @unit=mm 26 mm?></height>
caes0227.xml  <height><?not-yet-handling @exact=41 @unit=mm 41 mm?></height>
caes0228.xml  <height><?not-yet-handling Unknown?></height>
caes0230.xml  <height><?not-yet-handling @exact=30 @unit=mm ca. 30 mm?></height>
caes0242.xml  <height><?not-yet-handling Unknown?></height>
caes0243.xml  <height><?not-yet-handling @exact=82 @unit=mm 82 mm?></height>
caes0250.xml  <height><?not-yet-handling @exact=15 @unit=mm 15 mm?></height>
caes0251.xml  <height><?not-yet-handling @exact=20 @unit=mm 20 mm?></height>
caes0252.xml  <height><?not-yet-handling @exact=36 @unit=mm 36 mm?></height>
caes0253.xml  <height><?not-yet-handling @exact=65 @unit=mm ca. 65 mm?></height>
caes0255.xml  <height><?not-yet-handling @exact=35 @unit=mm 35 mm?></height>
caes0257.xml  <height><?not-yet-handling @unit=mm Unknown?></height>
caes0263.xml  <height><?not-yet-handling @exact=35 @unit=mm 35 mm?></height>
caes0272.xml  <height><?not-yet-handling @exact=35 @unit=mm 35 mm?></height>
caes0281.xml  <height><?not-yet-handling @exact=4 @unit=mm 4 mm?></height>
caes0283.xml  <height><?not-yet-handling @exact=34 @unit=mm 34 mm?></height>
caes0291.xml  <height><?not-yet-handling @exact=60 @unit=mm 60 mm?></height>
caes0302.xml  <height><?not-yet-handling @exact=32 @unit=mm 32 mm?></height>
caes0322.xml  <height><?not-yet-handling @exact=27 @unit=mm ca. 27 mm?></height>
caes0325.xml  <height><?not-yet-handling @exact=40 @unit=mm ca. 40 mm?></height>
caes0329.xml  <height><?not-yet-handling @exact=39 @unit=mm 39 mm?></height>
caes0330.xml  <height><?not-yet-handling Unknown?></height>
caes0336.xml  <height><?not-yet-handling @exact=40 @unit=mm 40 mm?></height>
caes0338.xml  <height><?not-yet-handling @exact=40 @unit=mm ca. 40 mm?></height>
caes0351.xml  <height><?not-yet-handling @exact=48 @unit=mm 48 mm?></height>
caes0354.xml  <height><?not-yet-handling @exact=95 @unit=mm 95 mm?></height>
caes0363.xml  <height><?not-yet-handling @exact=18 @unit=mm 18 mm?></height>
caes0366.xml  <height><?not-yet-handling @exact=0.10 @unit=m 0.10 m?></height>
caes0367.xml  <height><?not-yet-handling @exact=31 @unit=mm 31 mm?></height>
caes0370.xml  <height><?not-yet-handling @exact=40 @unit=mm ca. 40 mm?></height>
caes0371.xml  <height><?not-yet-handling Unknown?></height>
caes0372.xml  <height><?not-yet-handling Unknown?></height>
caes0380.xml  <height><?not-yet-handling @exact=70 @unit=mm ca. 70 mm?></height>
caes0385.xml  <height><?not-yet-handling @exact=25 @unit=mm ca. 25 mm?></height>
caes0386.xml  <height><?not-yet-handling @min=30 @max=43 @unit=mm ca. 30-43 mm?></height>
caes0390.xml  <height><?not-yet-handling @exact=33 @unit=mm 33 mm?></height>
caes0395.xml  <height><?not-yet-handling @exact=17 @unit=mm 17 mm?></height>
caes0396.xml  <height><?not-yet-handling @exact=40 @unit=mm ca. 40 mm?></height>
caes0398.xml  <height><?not-yet-handling @min=34 @max=35 @unit=mm ca. 34-35 mm?></height>
caes0405.xml  <height><?not-yet-handling @exact=40 @unit=mm ca. 40 mm?></height>
caes0407.xml  <height><?not-yet-handling @exact=32 @unit=mm 32 mm?></height>
caes0408.xml  <height><?not-yet-handling @exact=49 @unit=mm 49 mm?></height>
dabb0001.xml  <height><?not-yet-handling @exact=6 @unit=cm 6 cm?></height>
dabb0002.xml  <height><?not-yet-handling @exact=8 @unit=cm 8 cm?></height>
dabb0003.xml  <height><?not-yet-handling @exact=8 @unit=cm 8 cm?></height>
dabb0004.xml  <height><?not-yet-handling @exact=3 @unit=cm 3 cm?></height>
deir0001.xml  <height><?not-yet-handling @exact=8 @unit=cm 8 cm?></height>
edda0001.xml  <height><?not-yet-handling @exact=6 @unit=cm 6 cm?></height>
einn0004.xml  <height><?not-yet-handling @exact=5 @unit=cm 5 cm?></height>
eins0001.xml  <height><?not-yet-handling @exact=6 @unit=cm 6 cm?></height>
eins0002.xml  <height><?not-yet-handling @exact=8 @unit=cm 8 cm?></height>
elal0003.xml  <height><?not-yet-handling @exact=4 @unit=cm 4 cm?></height>
elal0004.xml  <height><?not-yet-handling @exact=6 @unit=cm 6 cm?></height>
elal0007.xml  <height><?not-yet-handling @exact=4 @unit=cm 4 cm?></height>
elal0008.xml  <height><?not-yet-handling @exact=6 @unit=cm 6 cm?></height>
elal0009.xml  <height><?not-yet-handling @exact=5 @unit=cm 5 cm?></height>
elal0010.xml  <height><?not-yet-handling @exact=4 @unit=cm 4 cm?></height>
elal0011.xml  <height><?not-yet-handling @exact=4.5 @unit=cm 4.5 cm?></height>
elal0013.xml  <height><?not-yet-handling @exact=6 @unit=cm 6 cm?></height>
elal0016.xml  <height><?not-yet-handling @exact=5 @unit=cm 5 cm?></height>
elal0017.xml  <height><?not-yet-handling @exact=3 @unit=cm 3 cm?></height>
elal0018.xml  <height><?not-yet-handling @exact=3 @unit=cm 3 cm?></height>
elal0019.xml  <height><?not-yet-handling @exact=5 @unit=cm 5 cm?></height>
elku0002.xml  <height><?not-yet-handling @exact=13 @unit=cm 13 cm?></height>
elus0006.xml  <height><?not-yet-handling @min=1.5 @max=1.5 @unit=cm 1.5 cm?></height>
elus0007.xml  <height><?not-yet-handling @exact=5 @unit=cm 5 cm?></height>
elus0009.xml  <height><?not-yet-handling @min=3 @max=3 @unit=cm 3 cm?></height>
elus0012.xml  <height><?not-yet-handling @min=5 @max=5 @unit=cm 5 cm?></height>
elus0013.xml  <height><?not-yet-handling @min=1.5 @max=1.5 @unit=cm 1.5 cm?></height>
elus0015.xml  <height><?not-yet-handling @min=3 @max=3 @unit=cm 3 cm?></height>
elus0016.xml  <height><?not-yet-handling @min=5 @max=5 @unit=cm 5 cm?></height>
elus0022.xml  <height><?not-yet-handling @min=2 @max=2 @unit=cm 2 cm?></height>
elus0024.xml  <height><?not-yet-handling @min=3 @max=3 @unit=cm 3 cm?></height>
elus0027.xml  <height><?not-yet-handling @min=6 @max=6 @unit=cm 6 cm?></height>
elus0033.xml  <height><?not-yet-handling @min=7 @max=7 @unit=cm 7 cm?></height>
elus0036.xml  <height><?not-yet-handling @min=4 @max=4 @unit=cm 4 cm?></height>
elus0041.xml  <height><?not-yet-handling @min=4 @max=4 @unit=cm 4 cm?></height>
elus0042.xml  <height><?not-yet-handling @min=5 @max=5 @unit=cm 5 cm?></height>
elus0045.xml  <height><?not-yet-handling @min=5 @max=5 @unit=cm 5 cm?></height>
elus0047.xml  <height><?not-yet-handling @min=unknown @max=unknown @unit=cm unknown?></height>
elus0048.xml  <height><?not-yet-handling @min=4.5 @max=4.5 @unit=cm 4.5 cm?></height>
elus0051.xml  <height><?not-yet-handling @min=1.5 @max=1.5 @unit=cm 1.5 cm?></height>
elus0052.xml  <height><?not-yet-handling @min=3 @max=3 @unit=cm 3 cm?></height>
elus0066.xml  <height><?not-yet-handling @min=2 @max=2 @unit=cm 2 cm?></height>
elus0074.xml  <height><?not-yet-handling @min=7 @max=7 @unit=cm 7 cm?></height>
elus0076.xml  <height><?not-yet-handling @min=4 @max=4 @unit=cm 4 cm?></height>
elus0078.xml  <height><?not-yet-handling @min=5 @max=5 @unit=cm 5 cm?></height>
elus0081.xml  <height><?not-yet-handling @min=0.5 @max=0.5 @unit=cm 0.5 cm?></height>
elus0086.xml  <height><?not-yet-handling @min=1.5 @max=1.5 @unit=cm 1.5 cm?></height>
elus0091.xml  <height><?not-yet-handling @min=2.3 @max=2.3 @unit=cm 2.3 cm?></height>
elus0094.xml  <height><?not-yet-handling @min=2 @max=2 @unit=cm 2 cm?></height>
elus0097.xml  <height><?not-yet-handling @min=1.5 @max=1.5 @unit=cm 1.5 cm?></height>
elus0098.xml  <height><?not-yet-handling @min=1 @max=1 @unit=cm 1 cm?></height>
elus0099.xml  <height><?not-yet-handling @min=1.3 @max=1.3 @unit=cm 1.3 cm?></height>
elus0101.xml  <height><?not-yet-handling @min=2.5 @max=2.5 @unit=cm 2.5 cm?></height>
elus0102.xml  <height><?not-yet-handling @min=1 @max=1 @unit=cm 1 cm?></height>
elus0103.xml  <height><?not-yet-handling @min=.5 @max=.5 @unit=cm 0.5 cm?></height>
elus0104.xml  <height><?not-yet-handling @min=.5 @max=.5 @unit=cm 0.5 cm?></height>
elus0105.xml  <height><?not-yet-handling @min=2 @max=2 @unit=cm 2 cm?></height>
eluy0001.xml  <height><?not-yet-handling unknown?></height>
eluy0002.xml  <height><?not-yet-handling unknown?></height>
eluy0003.xml  <height><?not-yet-handling unknown?></height>
emma0001.xml  <height><?not-yet-handling @min=4.5 @max=7 @unit=cm 4.5-7 cm (average 6 cm)?></height>
fakh0003.xml  <height><?not-yet-handling @exact=3 @unit=cm 3 cm?></height>
fakh0004.xml  <height><?not-yet-handling @exact=9 @unit=cm 9 cm?></height>
fakh0005.xml  <height><?not-yet-handling @exact=9 @unit=cm 9 cm?></height>
farj0003.xml  <height><?not-yet-handling @exact=7 @unit=cm 7 cm?></height>
farj0004.xml  <height><?not-yet-handling @exact=8 @unit=cm 8 cm?></height>
farj0005.xml  <height><?not-yet-handling @exact=45 @unit=cm 45 cm?></height>
fiqg0001.xml  <height><?not-yet-handling unknown?></height>
fiqg0002.xml  <height><?not-yet-handling 5 cm?></height>
fiqg0003.xml  <height><?not-yet-handling 5 cm?></height>
fiqg0004.xml  <height><?not-yet-handling 6 cm?></height>
fiqg0006.xml  <height><?not-yet-handling 6 cm?></height>
fiqg0009.xml  <height><?not-yet-handling 6 cm?></height>
fiqg0010.xml  <height><?not-yet-handling 6 cm?></height>
fiqg0011.xml  <height><?not-yet-handling 5 cm?></height>
fiqg0012.xml  <height><?not-yet-handling 8 cm?></height>
fiqg0014.xml  <height><?not-yet-handling 7 cm?></height>
fiqg0015.xml  <height><?not-yet-handling 5 cm?></height>
fiqg0016.xml  <height><?not-yet-handling 6 cm?></height>
fiqg0017.xml  <height><?not-yet-handling 5 cm?></height>
fiqg0020.xml  <height><?not-yet-handling 7 cm?></height>
fiqg0021.xml  <height><?not-yet-handling 5 cm?></height>
fiqg0022.xml  <height><?not-yet-handling 6 cm?></height>
fiqg0023.xml  <height><?not-yet-handling 4 cm?></height>
fiqg0024.xml  <height><?not-yet-handling 3 cm?></height>
fiqg0026.xml  <height><?not-yet-handling 4 cm?></height>
giva0001.xml  <height><?not-yet-handling @min=2 @max=2 @unit=cm 2 cm?></height>
hafa0002.xml  <height><?not-yet-handling @exact=6 @unit=cm 6 cm?></height>
halu0001.xml  <height><?not-yet-handling @min=1.7 @max=3.5 1.7-3.0 cm Aramaic, 2.5-3.5 cm Greek?></height>
hamm0001.xml  <height><?not-yet-handling 5.5 cm.?></height>
hamm0003.xml  <?not-yet-handling @unit=cm 3.4 cm.?>
hamm0005.xml  <?not-yet-handling @unit=cm 2.5 cm.?>
hamm0009.xml  <?not-yet-handling @unit=cm .?>
hamm0010.xml  <?not-yet-handling @unit=cm 3 cm.?>
hamm0021.xml  <height><?not-yet-handling @unit=cm 3 cm.?></height>
hamm0028.xml  <height><?not-yet-handling large?></height>
hamm0030.xml  <?not-yet-handling @min=4 @max=4 @unit=cm 4 cm?>
hamm0032.xml  <height><?not-yet-handling @min=5.5 @max=5.5 @unit=cm 5.5 cm?></height>
hamm0034.xml  <height><?not-yet-handling @min=4 @max=4 @unit=cm 4 cm?></height>
hamm0035.xml  <?not-yet-handling @min=4 @max=4 @unit=cm 4 cm?>
hamm0039.xml  <height><?not-yet-handling @min=3.6 @max=3.6 @unit=cm 3.6 cm?></height>
hamm0041.xml  <height><?not-yet-handling @min=5 @max=5 @unit=cm 5 cm?></height>
hamm0044.xml  <height><?not-yet-handling @min=3 @max=3 @unit=cm 3 cm?></height>
hamm0049.xml  <?not-yet-handling @min=5 @max=5 @unit=cm 5 cm?>
hamm0051.xml  <height><?not-yet-handling @min=5.5 @max=5.5 @unit=cm 5.5 cm?></height>
hamm0053.xml  <height><?not-yet-handling @min=5.5 @max=5.5 @unit=cm 5.5 cm?></height>
hamm0054.xml  <?not-yet-handling @min=3 @max=3 @unit=cm 3 cm?>
hamm0058.xml  <?not-yet-handling @min=2 @max=2 @unit=cm 2 cm?>
hamm0061.xml  <?not-yet-handling @min=3.5 @max=5.5 @unit=cm 3.5-5.5?>
hamm0065.xml  <height><?not-yet-handling @min=7 @max=7 @unit=cm 7 cm?></height>
hamm0066.xml  <height><?not-yet-handling @min=5 @max=5 @unit=cm 5 cm?></height>
hamm0067.xml  <height><?not-yet-handling @min=5 @max=5 @unit=cm 5 cm?></height>
hamm0070.xml  <height><?not-yet-handling @min=5 @max=5 @unit=cm 5 cm?></height>
juei0002.xml  <height><?not-yet-handling @exact=8 @unit=cm 8 cm?></height>
juei0003.xml  <height><?not-yet-handling @exact=6 @unit=cm 6 cm?></height>
juei0005.xml  <height><?not-yet-handling @exact=7 @unit=cm 7 cm?></height>
jurn0002.xml  <height><?not-yet-handling @exact=7 @unit=cm 7 cm?></height>
jurn0003.xml  <height><?not-yet-handling @exact=3 @unit=cm 3 cm?></height>
kafr0003.xml  <height><?not-yet-handling @exact=6 @unit=cm 6 cm?></height>
kafr0008.xml  <height><?not-yet-handling @exact=6 @unit=cm 6 cm?></height>
khis0071.xml  <height><?not-yet-handling @exact=5 @unit=cm 5 cm?></height>
khis0074.xml  <height><?not-yet-handling @exact=3 @unit=cm 3 cm?></height>
khis0076.xml  <height><?not-yet-handling @exact=5 @unit=cm 5 cm?></height>
khis0079.xml  <height><?not-yet-handling @exact=7 @unit=cm 7 cm?></height>
khis0081.xml  <height><?not-yet-handling @exact=11 @unit=cm 11 cm?></height>
khis0084.xml  <height><?not-yet-handling @exact=8 @unit=characters 8 cm?></height>
khis0087.xml  <height><?not-yet-handling @exact=7 @unit=characters 7 cm?></height>
khis0090.xml  <height><?not-yet-handling @exact=4 @unit=characters 4 cm?></height>
khus0003.xml  <height><?not-yet-handling @exact=5 @unit=cm 5 cm?></height>
mums0003.xml  <height><?not-yet-handling @exact=5 @unit=cm 5 cm?></height>
narr0001.xml  <height><?not-yet-handling 4 cm?></height>
narr0006.xml  <height><?not-yet-handling 10 cm?></height>
qast0001.xml  <height><?not-yet-handling @exact=10 10 cm?></height>
rafi0004.xml  <height><?not-yet-handling @exact=7 @unit=cm 7 cm?></height>
rafi0006.xml  <height><?not-yet-handling @exact=6.5 @unit=cm 6.5 cm?></height>
rafi0007.xml  <height><?not-yet-handling @exact=8 @unit=cm 8 cm?></height>
rafi0009.xml  <height><?not-yet-handling @exact=6 @unit=cm 6 cm?></height>
rafi0011.xml  <height><?not-yet-handling @exact=8 @unit=cm 8 cm?></height>
rafi0013.xml  <height><?not-yet-handling @exact=4 @unit=cm 4 cm?></height>
rasm0001.xml  <height><?not-yet-handling @exact=6 @unit=cm 6 cm?></height>
rujm0001.xml  <height><?not-yet-handling @exact=5 @unit=cm 5 cm?></height>
sepp0012.xml  <height><?not-yet-handling 5 cm?></height>
sepp0013.xml  <height><?not-yet-handling 6 cm in line 1 and 6.5 cm in line 2, I; 5.5 cm in line 1 and 6.5 cm in line 2, II?></height>
sepp0014.xml  <height><?not-yet-handling 6 cm?></height>
sepp0015.xml  <height><?not-yet-handling 6 cm?></height>
sepp0016.xml  <height><?not-yet-handling 7.5 cm?></height>
sepp0017.xml  <height><?not-yet-handling 5.5 cm?></height>
sepp0018.xml  <height><?not-yet-handling 5 cm?></height>
sepp0019.xml  <height><?not-yet-handling 6.5 cm?></height>
sepp0020.xml  <height><?not-yet-handling 5.5 cm?></height>
sepp0021.xml  <height><?not-yet-handling 6 cm?></height>
sepp0022.xml  <height><?not-yet-handling 6 cm?></height>
sepp0023.xml  <height><?not-yet-handling 5.5 cm?></height>
sepp0024.xml  <height><?not-yet-handling 5 cm?></height>
shea0001.xml  <height><?not-yet-handling @min=9.5 @max=11.5 @unit=cm 9.5-11.5?></height>
squf0001.xml  <height><?not-yet-handling @exact=5 @unit=cm 5 cm?></height>
squf0002.xml  <height><?not-yet-handling @exact=6 @unit=cm 6 cm?></height>
squf0003.xml  <height><?not-yet-handling @exact=5 @unit=cm 5 cm?></height>
suke0001.xml  <height><?not-yet-handling @exact=8 @unit=cm 8 cm?></height>
susi0001.xml  <height><?not-yet-handling unknown?></height>
susi0002.xml  <height><?not-yet-handling unknown?></height>
susi0003.xml  <height><?not-yet-handling unknown?></height>
susi0004.xml  <height><?not-yet-handling unknown?></height>
susi0005.xml  <height><?not-yet-handling unknown?></height>
susi0006.xml  <height><?not-yet-handling unknown?></height>
tala0003.xml  <height><?not-yet-handling @exact=8 @unit=cm 8 cm?></height>
tala0004.xml  <height><?not-yet-handling @exact=6 @unit=cm 6 cm?></height>
tell0001.xml  <height><?not-yet-handling @exact=7 @unit=cm 7 cm?></height>
zoor0204.xml  <height><?not-yet-handling Unrecorded?></height>
zoor0222.xml  <height><?not-yet-handling unrecorded?></height>
zoor0291.xml  <height><?not-yet-handling @min=0.000 @max=0.000 @unit=m Unrecorded?></height>
zoor0300.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0322.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0323.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0324.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0325.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0326.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0327.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0328.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0329.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0330.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0331.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0332.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0333.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0334.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0335.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0336.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0337.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0338.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0339.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0340.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0341.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0342.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0343.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0344.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0345.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0346.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0347.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0348.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unknown?></height>
zoor0349.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0350.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0351.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0352.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>
zoor0353.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unknown?></height>
zoor0354.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unknown?></height>
zoor0355.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unknown?></height>
zoor0356.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unknown?></height>
zoor0357.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unknown?></height>
zoor0358.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unknown?></height>
zoor0359.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unknown?></height>
zoor0360.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unknown?></height>
zoor0361.xml  <height><?not-yet-handling @min=0.00 @max=0.00 @unit=m Unrecorded?></height>

**Comment by GaiaLembi** [comment]
Please make them match the current template.
If there are things you cannot change automatically, do send a list and I'll fix them manually.

**Comment by emylonas** [comment]
closing with  c050766

**Comment by emylonas** [comment]
Last two letter measurements that are odd - 
```
halu0001.xml
<height><?not-yet-handling @min=1.7 @max=3.5 1.7-3.0 cm Aramaic, 2.5-3.5 cm Greek?></height>

sepp0013.xml
<height><?not-yet-handling 6 cm in line 1 and 6.5 cm in line 2, I; 5.5 cm in line 1 and 6.5 cm in line 2, II?></height>
```

Perhaps make them more regular, (for ex. min max would be from the smallest to the largest regardless of language in halu0001, and then add details in a note? Same approach for sepp0013?

**Comment by emylonas** [comment]
Gaia has fixed
