### ISSUE TITLE
hamm inscriptions have greek transcriptions written in latin alphabet

### ISSUE THREAD

**Issue by crotger** [Brown-University-Library/iip-texts#2]
hamm0010, hamm0012, hamm0030, hamm0037 all have mixed latin and greek alphabet even though they are written in greek.

https://github.com/Brown-University-Library/iip-texts/search?utf8=%E2%9C%93&q=add&type=Code

They also have `<add>aboves</add>` elements that should probably be `<add place="above">σ</add>`

**Comment by emylonas** [comment]
closed, same as  #31
