### ISSUE TITLE
jaffa greek going rtl

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#20]
There are a number of jaffa inscriptions, for ex. 24 (partially fixed) that either have no Hebrew or have a single Hebrew word. However, they were marked up using the Hebrew template and so the Greek goes rtl. We need to remove the ` xml:lang="heb"` from the paragraph, and add it only to the single Hebrew word.

**Comment by GaiaLembi** [comment]
Do you have a list? Otherwise, I will check them one by one and fix the issue.

**Comment by emylonas** [comment]
I can try to look for them, just noticed them when I was looking at the new search results view.

**Comment by GaiaLembi** [comment]
Done.
I noticed, however, that not all the Jaffa inscriptions come up in the results on the website, despite the fact that all of them are in versioned. Can you please check why this is happening?

**Comment by emylonas** [comment]
some are not approved yet. however all are there. closing
