### ISSUE TITLE
Phyisical Type "stone"

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#26]
From mail on Dec. 16:
The inscriptions that have the value "stone" for their object type are probably all sorts of things like tombstones, boundary stones and so on. There are 21 of them (just select "stone" in the object box on our search page.)  I think we can move many if not all of them into various other categories.

**Comment by emylonas** [comment]
This is the list of files that have that value: 
https://library.brown.edu/cds/projects/iip/results/?q=physical_type:(stone)

**Comment by GaiaLembi** [comment]
All done except CAES0205 and CAES0206 (waiting for the book).

**Comment by GaiaLembi** [comment]
All Done
