### ISSUE TITLE
beth0005 dimensions inconsistent

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#29]
beth0005 has: 
```
<support>
  <dimensions type="surface" unit="cm">
     <height quantity="36">18</height>
    <width quantity="18">36</width>
  </dimensions>
  <p/>
 </support>
```

the attribute value and the content of height and width are "crossed" Not sure which is correct, but need to put that value in the content and delete the `@quantity` attribute.

**Comment by GaiaLembi** [comment]
Height is 18 cm, width is 36 cm.
Corrected.
