### ISSUE TITLE
masa0038 not what it seems

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#30]
There is, however, a huge issue with masa0038, in that the name the file was saved with doesn't correspond to the actual ID in the xml. I will redo it altogether

from #12

**Comment by emylonas** [comment]
masa0038 and masa0508 are confused - see text and biblScope. Gaia has to check on return to Providence.

**Comment by GaiaLembi** [comment]
Masa0037 to Masa0039 have been cancelled (duplicates: please double check they're gone). Masa0508 is fine
