### ISSUE TITLE
Zoora in locations menu on Search Page

### ISSUE THREAD

**Issue by GaiaLembi** [Brown-University-Library/iip-texts#41]
Zoora appears twice, with the same region (Negev).
Data need to be corrected for those inscriptions which bear "Zoora, Eastern shore of the Dead Sea"

**Comment by emylonas** [comment]
I am mystified by the double Zoora, I've looked for spaces, capitalization and can't find the discrepancy. Will try again. 

What should Zoar,  Eastern shore of the Dead Sea become? what is its region? It's not Zoor, but Zoar. Also has no Pleiades ID.

**Comment by GaiaLembi** [comment]
Zoora and Zoar are the same place.
Zoar0001 and Zoar0002 have been published anew in vol. 1c of "Inscriptions from Palaestina Tertia. The Jewish Aramaic Inscriptions from Ghor Es-Safi (Byzantine Zoora)", which students should work on next academic year. Alas, this volume has only transcriptions (no Hebrew characters) and translations, which doesn't make much sense -- in fact, Sacha Stern harshly criticized this choice in his review of the volume.

**Comment by GaiaLembi** [comment]
One more issue, related to Zoar0002: if you type Hannah in the Text Search, this inscription is not shown.
I start suspecting we do have some issues to deal with when it comes to Text Search :-(

**Comment by emylonas** [comment]
I am changing the region and settlement in the two zoar inscriptions to 
```
<region>Negev</region>
<settlement ref="http://pleiades.stoa.org/places/697768">Zoar</settlement>
```

Or should I change Zoar to Zoor as well?

**Comment by emylonas** [comment]
Change Zoar inscriptions as follows:

- settlement is Zoora not Zoar
- Pleiades ID remains the same
- IIP ID is zoar0001 becomes zoor0362
- IIP ID is zoar0002 becomes zoor0363

**Comment by emylonas** [comment]
done, but waiting to close until it's indexed.

**Comment by emylonas** [comment]
no zoar inscriptions left. seem to be indexing ok fixed with commit4e4bee7
