### ISSUE TITLE
Maresha/Marisa

### ISSUE THREAD

**Issue by GaiaLembi** [Brown-University-Library/iip-texts#42]
Elli, 
if you look at the Locations, Marisa appears twice: once as being in the Shephelah, once as being in the Negev.
Negev is definitely wrong. Technically it is in the Shephelah, a transitional region between Judaea and the Coastal Plain, but we haven't included it in our Regions List.
Since all the other inscriptions from Maresha have been entered with Judaea as region, I would uniform Mari0001 to Mari0005 to them.
Also, please cancel Mari0101 and Mari0006: they are identical and the same inscription has been better re-encoded as Mare0136

**Comment by emylonas** [comment]
files deleted, all mari files have Judaea in the region element.
