### ISSUE TITLE
bib data consistency

### ISSUE THREAD

**Issue by birkin** [Brown-University-Library/iip-texts#44]
- note: the data consistency issue does _not_ cause display issues for the [current production site](https://library.brown.edu/cds/projects/iip/) -- only for the [student-development site](http://dcdscit.services.brown.edu/iip_smr_dev/)

- detailed info about the issue, with examples, is in the [github issue in the student-development-site](https://github.com/Brown-University-Library/iip_smr_web_project/issues/1)

**Comment by birkin** [comment]
- spoke w/E.M. about this; E.M. will make the data consistent rather than handle the inconsistency via code.

**Comment by emylonas** [comment]
Lots of bib items were

1.  lacking the .xml extension. Not sure why we still have it, but it seems to be required
1. lacking the `@type="biblItem"` attribute. 

Have added both. 

I also found these bib items with old IDs or no IDs
```
beth0061.xml: <ptr type="biblItem" target="lifshitz1960b"/>
beth0146.xml: <ptr type="biblItem" target="SEG"/>
beth0163.xml: <ptr type="biblItem" target="SEG"/>
beth0176.xml: <ptr type="biblItem" target="Bull"/>
bshe0103.xml: <ptr target="IEJ1988c"/>
bshe0103.xml: <ptr target="IEJ1988c"/>
mger0002.xml: <ptr/>
mger0307.xml: <ptr/>
tqas0001.xml: <ptr target="IEJ1985"/>
tqas0002.xml: <ptr target="IEJ1985a"/>
```

**Comment by emylonas** [comment]
@birkin curious why the change in bibliography handling. Glad it found inconsistencies, which I've fixed barring the 8 references above.

**Comment by emylonas** [comment]
@GaiaLembi 
I have corrected
'''
bshe0103.xml: <ptr target="IEJ1988c"/>
bshe0103.xml: <ptr target="IEJ1988c"/>
tqas0002.xml: <ptr target="IEJ1985a"/>
'''
I think lifshitz1960b is IIP-263.xml
iej1985 is probably !!P-538 but note that there are two Zotero entries marked IEJ1985a...
The two SEG items need to be found in the Supplementum. 
Bull is some Bulletin Epigraphique.

**Comment by emylonas** [comment]
This is what's left:
```
beth0061.xml: <ptr type="biblItem" target="lifshitz1960b"/>
beth0146.xml: <ptr type="biblItem" target="SEG"/>
beth0163.xml: <ptr type="biblItem" target="SEG"/>
beth0176.xml: <ptr type="biblItem" target="Bull"/>
```

**Comment by emylonas** [comment]
fixed lifshitz1960b, removed the others as they are not solvable.
