### ISSUE TITLE
"https" in pleiades url instead of "http"

### ISSUE THREAD

**Issue by WennieZ** [Brown-University-Library/iip-texts#45]
There are 59 inscriptions at the location corresponding to the pleiades id 687966. However, mare0086 has "**https**://pleiades.stoa.org/places/687966" in the pleiades url field while the other 58 inscriptions have "**http**://pleiades.stoa.org/places/687966". mare0086 is the only inscription in the database that has a pleiades url with https instead of http. This inconsistency should be corrected because it is resulting in 2 circles being plotted on the map corresponding to location 687966.

**Comment by emylonas** [comment]
Will do!

Elli Mylonas

[Sent from my phone, please excuse typos or autocorrect]

**Comment by emylonas** [comment]
closing with e2056fd
