### ISSUE TITLE
TKERI0001 and TKERI0002

### ISSUE THREAD

**Issue by WennieZ** [Brown-University-Library/iip-texts#47]
These inscriptions do not follow the rule for inscription ID formatting.

**Comment by emylonas** [comment]
Good point. Will handle on Monday

Elli Mylonas

[Sent from my phone, please excuse typos or autocorrect]

**Comment by emylonas** [comment]
@GaiaLembi should we make these be tker or tkri? It's not technically a problem to have 5 characters in the abbreviation, but if someone is looking for 4chars+4nums as an id, these will be overlooked.

**Comment by emylonas** [comment]
@GaiaLembi  says: tker

**Comment by emylonas** [comment]
fixed
