### ISSUE TITLE
Cannot access images in our database

### ISSUE THREAD

**Issue by dk58** [Brown-University-Library/iip-texts#48]
https://github.com/Brown-University-Library/iip-texts/blob/7a59adba5b242d455e751d97f51a041f2c83bcd0/iip_to_solr.xsl#L37

Is this because images are not indexed yet? (The line 37 is commented out).

**Comment by emylonas** [comment]
yes

[Elli Mylonas
 Senior Digital Humanities Librarian
 and
 Center for Digital Scholarship
 University Library
 Brown University
 library.brown.edu/cds]

On Mon, Oct 2, 2017 at 5:48 PM, Dae Hyun (Sam) Kim <notifications@github.com
