### ISSUE TITLE
orig alone formatting in transcription

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#50]
when there is no `<choice>` or `<reg>` the text inside the `<orig>` should be capitalized.

**Comment by kjin97** [comment]
Simply add these lines to the CSS:

`tei-orig {
  text-transform: capitalize;
}
tei-choice tei-orig {
  text-transform: none;
}`

A much more elegant solution
`tei-orig:not(:has(tei-choice >)) {}` 
is possible with Selectors level 4, which is unfortunately still in development.

**Comment by emylonas** [comment]
sorry, didnt' mean Capitalize, meant ALL CAPS

**Comment by emylonas** [comment]
This works now. closing
