### ISSUE TITLE
sic/corr and orig/reg are not showing up correctly

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#54]
we see both forms in display see zoor 0369. Should only see the corr or reg

**Comment by GaiaLembi** [comment]
Elli, 
I noticed that actually in haif0040 the sic/corr IS being displayed correctly (i.e. only the correct form shows on the website). I wonder why this stopped working with inscriptions entered later on

**Comment by kjin97** [comment]
Currently, tei_custom_elements handles sic/corr but not orig/reg. Should just be a couple lines fix by adding the same behaviour for orig/reg as sic/corr if that's what's wanted.

**Comment by emylonas** [comment]
great - @GaiaLembi  may send you some editorial marks to put around the displayed word.

**Comment by emylonas** [comment]
This works now, closing
