### ISSUE TITLE
Zotero Group

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#58]
use Zotero Group, not Zotero user

**Comment by zaaakk** [comment]
fixed but not pushed :)

**Comment by GaiaLembi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Zotero sync issues](https://trello.com/c/jikyqhBq/11-zotero-sync-issues)

**Comment by emylonas** [comment]
fixed
