### ISSUE TITLE
strange location names and behavior

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#60]
maon0001 has Ḥorbat Ma'on as the settlement name There is a dot under the H which is making it sort after Zoora in the list of locations. Is that correct? There are some other settlements called Horvat xxx with no dotted H.

caes0501, 0502, 0506, 0506, 0508, 0509, 0515-0517 have Caesarea as the `<region>`, not as the `<settlement>`

caes0503-0505 have no region at all, and Caesarea appears correctly as the settlement.

mare0082, 0084, 0193 have neither settlement nor region.

bshe0022, 0024, 0025 have `<settlement>` as Beth Shean, not Scythopolis-Beth Shean

idum files have neither `region` nor `settlement`, the region should be Negev, I think.

geze files mostly have Gazara (Gezer) in the summary, and Gazara in `<settlement>`. but geze0100 has Gezer in  `<settlement>`

**Comment by emylonas** [comment]
egal0001 had no settlement info and the Pleiades id wasn't filled in. I copied this information in from egal0002.

**Comment by emylonas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Correct the counts for "place" on the search page of the new site.](https://trello.com/c/IDJq9iNI/34-correct-the-counts-for-place-on-the-search-page-of-the-new-site)

**Comment by emylonas** [comment]
From an old email:
EM: shea0001 appears to be a Beth Shean inscription, but instead of bshe it's shea. The note on the origin says "Jordan Valley. Beth Shean. In the yard of the monastery near Kibbutz Mesilo" 
GL: If it's only one instance we can change it to Bshe with  an appropriate number.

We never resolved the Maresha/Marisa question. There are about 8 mari000 inscriptions in which the `<settlement>` is spelled "Marisa" and a some hundreds mare0000 inscriptions where the `<settlement>` is spelled Maresha. No problem, but might want to pick on spelling if it's the same place. 

Note that when deleting, best to remove the files that will be renamed, then commit/push, then edit th files to have new names and add them back in and again, commit/push

**Comment by GaiaLembi** [comment]
For consistency, I changed Ḥorbat to Horvat in maon0001

**Comment by GaiaLembi** [comment]
Marisa and Maresha are the same (see Pleiades ID): since most inscriptions from this place has "Maresha", I changed Marisa to Maresha in mari0001 to mari0005. Mari0100, on the other hand, stands out for weirdness, because the place is Scythopolis-Beth Shean, so I do not understand where the ID Marixxxx comes from

**Comment by GaiaLembi** [comment]
I made all the requested changes except for the Idum series: once you have done so, the issue can be closed

**Comment by emylonas** [comment]
Idum series is fine - I think it must have been my mistake. Or I fixed it and forgot that I had done. it. They are all <region>Negev</region> now. closed with 55edc0c2
