### ISSUE TITLE
abbreviations not done properly

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#61]
Some of these may have been fixed  

 akld0018.xml Description: all text in expan should be in abbr or ex
 beth0020.xml Description: all text in expan should be in abbr or ex
 beth0036.xml Description: all text in expan should be in abbr or ex
 bshe0009.xml Description: all text in expan should be in abbr or ex
 bshe0010.xml Description: all text in expan should be in abbr or ex
 bshe0012.xml Description: all text in expan should be in abbr or ex
 bshe0023.xml Description: all text in expan should be in abbr or ex
 bshe0144.xml Description: all text in expan should be in abbr or ex
 bshe0144.xml Description: all text in expan should be in abbr or ex
 caes0005.xml Description: all text in expan should be in abbr or ex
 caes0005.xml Description: all text in expan should be in abbr or ex
 caes0006.xml Description: all text in expan should be in abbr or ex
 caes0006.xml Description: all text in expan should be in abbr or ex
 caes0007.xml Description: all text in expan should be in abbr or ex
 caes0008.xml Description: all text in expan should be in abbr or ex
 caes0008.xml Description: all text in expan should be in abbr or ex
 caes0016.xml Description: all text in expan should be in abbr or ex
 caes0016.xml Description: all text in expan should be in abbr or ex
 caes0016.xml Description: all text in expan should be in abbr or ex
 caes0016.xml Description: all text in expan should be in abbr or ex
 caes0016.xml Description: all text in expan should be in abbr or ex
 caes0016.xml Description: all text in expan should be in abbr or ex
 caes0018.xml Description: all text in expan should be in abbr or ex
 caes0018.xml Description: all text in expan should be in abbr or ex
 caes0018.xml Description: all text in expan should be in abbr or ex
 caes0018.xml Description: all text in expan should be in abbr or ex
 caes0019.xml Description: all text in expan should be in abbr or ex
 caes0020.xml Description: all text in expan should be in abbr or ex
 caes0020.xml Description: all text in expan should be in abbr or ex
 caes0021.xml Description: all text in expan should be in abbr or ex
 caes0022.xml Description: all text in expan should be in abbr or ex
 caes0027.xml Description: all text in expan should be in abbr or ex
 caes0027.xml Description: all text in expan should be in abbr or ex
 caes0027.xml Description: all text in expan should be in abbr or ex
 caes0029.xml Description: all text in expan should be in abbr or ex
 caes0030.xml Description: all text in expan should be in abbr or ex
 caes0032.xml Description: all text in expan should be in abbr or ex
 caes0032.xml Description: all text in expan should be in abbr or ex
 caes0032.xml Description: all text in expan should be in abbr or ex
 caes0032.xml Description: all text in expan should be in abbr or ex
 caes0033.xml Description: all text in expan should be in abbr or ex
 caes0033.xml Description: all text in expan should be in abbr or ex
 caes0034.xml Description: all text in expan should be in abbr or ex
 caes0035.xml Description: all text in expan should be in abbr or ex
 caes0035.xml Description: all text in expan should be in abbr or ex
 caes0035.xml Description: all text in expan should be in abbr or ex
 caes0036.xml Description: all text in expan should be in abbr or ex
 caes0049.xml Description: all text in expan should be in abbr or ex
 caes0049.xml Description: all text in expan should be in abbr or ex
 caes0058.xml Description: all text in expan should be in abbr or ex
 caes0058.xml Description: all text in expan should be in abbr or ex
 caes0058.xml Description: all text in expan should be in abbr or ex
 caes0079.xml Description: all text in expan should be in abbr or ex
 caes0090.xml Description: all text in expan should be in abbr or ex
 caes0090.xml Description: all text in expan should be in abbr or ex
 caes0090.xml Description: all text in expan should be in abbr or ex
 caes0119.xml Description: all text in expan should be in abbr or ex
 caes0127.xml Description: all text in expan should be in abbr or ex
 caes0148.xml Description: all text in expan should be in abbr or ex
 caes0200.xml Description: all text in expan should be in abbr or ex
 caes0206.xml Description: all text in expan should be in abbr or ex
 caes0208.xml Description: all text in expan should be in abbr or ex
 caes0232.xml Description: all text in expan should be in abbr or ex
 caes0291.xml Description: all text in expan should be in abbr or ex
 caes0303.xml Description: all text in expan should be in abbr or ex
 caes0350.xml Description: all text in expan should be in abbr or ex
 caes0350.xml Description: all text in expan should be in abbr or ex
 caes0351.xml Description: all text in expan should be in abbr or ex
 deir0001.xml Description: all text in expan should be in abbr or ex
 elal0007.xml Description: all text in expan should be in abbr or ex
 elal0008.xml Description: all text in expan should be in abbr or ex
 elal0010.xml Description: all text in expan should be in abbr or ex
 elal0012.xml Description: all text in expan should be in abbr or ex
 elal0013.xml Description: all text in expan should be in abbr or ex
 elme0002.xml Description: all text in expan should be in abbr or ex
 elus0015.xml Description: all text in expan should be in abbr or ex
 elus0015.xml Description: all text in expan should be in abbr or ex
 elus0018.xml Description: all text in expan should be in abbr or ex
 elus0032.xml Description: all text in expan should be in abbr or ex
 elus0039.xml Description: all text in expan should be in abbr or ex
 elus0043.xml Description: all text in expan should be in abbr or ex
 elus0044.xml Description: all text in expan should be in abbr or ex
 elus0049.xml Description: all text in expan should be in abbr or ex
 elus0058.xml Description: all text in expan should be in abbr or ex
 elus0059.xml Description: all text in expan should be in abbr or ex
 elus0087.xml Description: all text in expan should be in abbr or ex
 elus0093.xml Description: all text in expan should be in abbr or ex
 evro0013.xml Description: all text in expan should be in abbr or ex
 fakh0004.xml Description: all text in expan should be in abbr or ex
 farj0002.xml Description: all text in expan should be in abbr or ex
 jeru0083.xml Description: all text in expan should be in abbr or ex
 jeru0196.xml Description: all text in expan should be in abbr or ex
 jeru0320.xml Description: all text in expan should be in abbr or ex
 jeru0321.xml Description: all text in expan should be in abbr or ex
 jeru0322.xml Description: all text in expan should be in abbr or ex
 jeru0323.xml Description: all text in expan should be in abbr or ex
 jeru0324.xml Description: all text in expan should be in abbr or ex
 jeru0325.xml Description: all text in expan should be in abbr or ex
 jeru0426.xml Description: all text in expan should be in abbr or ex
 jeru0426.xml Description: all text in expan should be in abbr or ex
 jeru0426.xml Description: all text in expan should be in abbr or ex
 jeru0491.xml Description: all text in expan should be in abbr or ex
 jmon0026.xml Description: all text in expan should be in abbr or ex
 juda0001.xml Description: all text in expan should be in abbr or ex
 juda0001.xml Description: all text in expan should be in abbr or ex
 kede0003.xml Description: all text in expan should be in abbr or ex
 khis0071.xml Description: all text in expan should be in abbr or ex
 khis0081.xml Description: all text in expan should be in abbr or ex
 khis0082.xml Description: all text in expan should be in abbr or ex
 mare0189.xml Description: all text in expan should be in abbr or ex
 mare0216.xml Description: all text in expan should be in abbr or ex
 mare0245.xml Description: all text in expan should be in abbr or ex
 rafi0005.xml Description: all text in expan should be in abbr or ex
 rafi0007.xml Description: all text in expan should be in abbr or ex
 sina0108.xml Description: all text in expan should be in abbr or ex
 squf0003.xml Description: all text in expan should be in abbr or ex
 squf0003.xml Description: all text in expan should be in abbr or ex
 suke0001.xml Description: all text in expan should be in abbr or ex
 tbye0001.xml Description: all text in expan should be in abbr or ex
 tbye0001.xml Description: all text in expan should be in abbr or ex
 tdor0003.xml Description: all text in expan should be in abbr or ex
 tdor0003.xml Description: all text in expan should be in abbr or ex
 tdor0003.xml Description: all text in expan should be in abbr or ex
 tdor0003.xml Description: all text in expan should be in abbr or ex
 tqas0001.xml Description: all text in expan should be in abbr or ex
 tqas0001.xml Description: all text in expan should be in abbr or ex
 tqas0001.xml Description: all text in expan should be in abbr or ex
 tqas0001.xml Description: all text in expan should be in abbr or ex
 tqas0001.xml Description: all text in expan should be in abbr or ex
 tqas0001.xml Description: all text in expan should be in abbr or ex
 tqas0003.xml Description: all text in expan should be in abbr or ex
 tqas0003.xml Description: all text in expan should be in abbr or ex
 tqas0003.xml Description: all text in expan should be in abbr or ex
 tqas0003.xml Description: all text in expan should be in abbr or ex
 tqas0003.xml Description: all text in expan should be in abbr or ex
 tqas0003.xml Description: all text in expan should be in abbr or ex
 yotv0001.xml Description: all text in expan should be in abbr or ex
 yotv0001.xml Description: all text in expan should be in abbr or ex
 yotv0001.xml Description: all text in expan should be in abbr or ex
 yotv0001.xml Description: all text in expan should be in abbr or ex
 yotv0001.xml Description: all text in expan should be in abbr or ex
 yotv0001.xml Description: all text in expan should be in abbr or ex
 yotv0001.xml Description: all text in expan should be in abbr or ex
 zoor0001.xml Description: all text in expan should be in abbr or ex
 zoor0001.xml Description: all text in expan should be in abbr or ex
 zoor0005.xml Description: all text in expan should be in abbr or ex
 zoor0011.xml Description: all text in expan should be in abbr or ex
 zoor0035.xml Description: all text in expan should be in abbr or ex
 zoor0037.xml Description: all text in expan should be in abbr or ex
 zoor0040.xml Description: all text in expan should be in abbr or ex
 zoor0040.xml Description: all text in expan should be in abbr or ex
 zoor0040.xml Description: all text in expan should be in abbr or ex
 zoor0047.xml Description: all text in expan should be in abbr or ex
 zoor0067.xml Description: all text in expan should be in abbr or ex
 zoor0075.xml Description: all text in expan should be in abbr or ex
 zoor0099.xml Description: all text in expan should be in abbr or ex
 zoor0099.xml Description: all text in expan should be in abbr or ex
 zoor0104.xml Description: all text in expan should be in abbr or ex
 zoor0115.xml Description: all text in expan should be in abbr or ex
 zoor0116.xml Description: all text in expan should be in abbr or ex
 zoor0129.xml Description: all text in expan should be in abbr or ex
 zoor0145.xml Description: all text in expan should be in abbr or ex
 zoor0165.xml Description: all text in expan should be in abbr or ex
 zoor0165.xml Description: all text in expan should be in abbr or ex
 zoor0165.xml Description: all text in expan should be in abbr or ex
 zoor0182.xml Description: all text in expan should be in abbr or ex
 zoor0182.xml Description: all text in expan should be in abbr or ex
 zoor0184.xml Description: all text in expan should be in abbr or ex
 zoor0187.xml Description: all text in expan should be in abbr or ex
 zoor0196.xml Description: all text in expan should be in abbr or ex
 zoor0197.xml Description: all text in expan should be in abbr or ex
 zoor0199.xml Description: all text in expan should be in abbr or ex
 zoor0199.xml Description: all text in expan should be in abbr or ex
 zoor0202.xml Description: all text in expan should be in abbr or ex
 zoor0203.xml Description: all text in expan should be in abbr or ex
 zoor0203.xml Description: all text in expan should be in abbr or ex
 zoor0203.xml Description: all text in expan should be in abbr or ex
 zoor0209.xml Description: all text in expan should be in abbr or ex
 zoor0219.xml Description: all text in expan should be in abbr or ex
 zoor0242.xml Description: all text in expan should be in abbr or ex
 zoor0243.xml Description: all text in expan should be in abbr or ex
 zoor0245.xml Description: all text in expan should be in abbr or ex
 zoor0245.xml Description: all text in expan should be in abbr or ex
 zoor0257.xml Description: all text in expan should be in abbr or ex
 zoor0257.xml Description: all text in expan should be in abbr or ex
 zoor0261.xml Description: all text in expan should be in abbr or ex
 zoor0262.xml Description: all text in expan should be in abbr or ex
 zoor0262.xml Description: all text in expan should be in abbr or ex
 zoor0270.xml Description: all text in expan should be in abbr or ex
 zoor0289.xml Description: all text in expan should be in abbr or ex

**Comment by GaiaLembi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Abbreviations not done properly](https://trello.com/c/i6ivU6KN/51-abbreviations-not-done-properly)
