### ISSUE TITLE
angle brackets and other characters in epigraphic text

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#62]
This is related to #23 

 abil0001.xml Description: Brackets and parentheses in epigraphic text
 abil0001.xml Description: Brackets and parentheses in epigraphic text
 ashk0001.xml Description: Brackets and parentheses in epigraphic text
 ashk0001.xml Description: Brackets and parentheses in epigraphic text
 baid0001.xml Description: Brackets and parentheses in epigraphic text
 baid0001.xml Description: Brackets and parentheses in epigraphic text
 beth0106.xml Description: Brackets and parentheses in epigraphic text
 beth0106.xml Description: Brackets and parentheses in epigraphic text
 beth0149.xml Description: Brackets and parentheses in epigraphic text
 beth0149.xml Description: Brackets and parentheses in epigraphic text
 beth0195.xml Description: Angle brackets in epigraphic text
 beth0195.xml Description: Angle brackets in epigraphic text
 beth0198.xml Description: Brackets and parentheses in epigraphic text
 beth0198.xml Description: Brackets and parentheses in epigraphic text
 beth0210.xml Description: Brackets and parentheses in epigraphic text
 beth0210.xml Description: Brackets and parentheses in epigraphic text
 beth0258.xml Description: Angle brackets in epigraphic text
 beth0258.xml Description: Angle brackets in epigraphic text
 bshe0014.xml Description: Brackets and parentheses in epigraphic text
 bshe0014.xml Description: Brackets and parentheses in epigraphic text
 bshe0030.xml Description: Brackets and parentheses in epigraphic text
 bshe0030.xml Description: Brackets and parentheses in epigraphic text
 caes0004.xml Description: Angle brackets in epigraphic text
 caes0004.xml Description: Angle brackets in epigraphic text
 caes0023.xml Description: Angle brackets in epigraphic text
 caes0023.xml Description: Angle brackets in epigraphic text
 caes0044.xml Description: Brackets and parentheses in epigraphic text
 caes0044.xml Description: Brackets and parentheses in epigraphic text
 caes0111.xml Description: Angle brackets in epigraphic text
 caes0111.xml Description: Angle brackets in epigraphic text
 caes0231.xml Description: Brackets and parentheses in epigraphic text
 caes0231.xml Description: Brackets and parentheses in epigraphic text
 caes0331.xml Description: Brackets and parentheses in epigraphic text
 caes0331.xml Description: Brackets and parentheses in epigraphic text
 caes0503.xml Description: Brackets and parentheses in epigraphic text
 caes0503.xml Description: Brackets and parentheses in epigraphic text
 deir0001.xml Description: Brackets and parentheses in epigraphic text
 deir0001.xml Description: Brackets and parentheses in epigraphic text
 elal0007.xml Description: Angle brackets in epigraphic text
 elal0007.xml Description: Angle brackets in epigraphic text
 elal0008.xml Description: Brackets and parentheses in epigraphic text
 elal0008.xml Description: Brackets and parentheses in epigraphic text
 elal0012.xml Description: Brackets and parentheses in epigraphic text
 elal0012.xml Description: Brackets and parentheses in epigraphic text
 elji0002.xml Description: Brackets and parentheses in epigraphic text
 elji0002.xml Description: Brackets and parentheses in epigraphic text
 elus0016.xml Description: Brackets and parentheses in epigraphic text
 elus0016.xml Description: Brackets and parentheses in epigraphic text
 fakh0004.xml Description: Angle brackets in epigraphic text
 fakh0004.xml Description: Angle brackets in epigraphic text
 fiqg0018.xml Description: Angle brackets in epigraphic text
 fiqg0018.xml Description: Angle brackets in epigraphic text
 geze0008.xml Description: Brackets and parentheses in epigraphic text
 geze0008.xml Description: Brackets and parentheses in epigraphic text
 haif0048.xml Description: Angle brackets in epigraphic text
 haif0048.xml Description: Angle brackets in epigraphic text
 haif0049.xml Description: Angle brackets in epigraphic text
 haif0049.xml Description: Angle brackets in epigraphic text
 idum0044.xml Description: Brackets and parentheses in epigraphic text
 idum0044.xml Description: Brackets and parentheses in epigraphic text
 idum0210.xml Description: Angle brackets in epigraphic text
 idum0210.xml Description: Angle brackets in epigraphic text
 jeri0011.xml Description: Brackets and parentheses in epigraphic text
 jeri0011.xml Description: Brackets and parentheses in epigraphic text
 jeru0016.xml Description: Brackets and parentheses in epigraphic text
 jeru0016.xml Description: Brackets and parentheses in epigraphic text
 jeru0016.xml Description: Brackets and parentheses in epigraphic text
 jeru0016.xml Description: Brackets and parentheses in epigraphic text
 jeru0051.xml Description: Brackets and parentheses in epigraphic text
 jeru0051.xml Description: Brackets and parentheses in epigraphic text
 jeru0055.xml Description: Brackets and parentheses in epigraphic text
 jeru0055.xml Description: Brackets and parentheses in epigraphic text
 jeru0083.xml Description: Brackets and parentheses in epigraphic text
 jeru0083.xml Description: Brackets and parentheses in epigraphic text
 jeru0107.xml Description: Brackets and parentheses in epigraphic text
 jeru0107.xml Description: Brackets and parentheses in epigraphic text
 jord0001.xml Description: Angle brackets in epigraphic text
 jord0001.xml Description: Angle brackets in epigraphic text
 kafr0003.xml Description: Brackets and parentheses in epigraphic text
 kafr0003.xml Description: Brackets and parentheses in epigraphic text
 khis0082.xml Description: Angle brackets in epigraphic text
 khis0082.xml Description: Angle brackets in epigraphic text
 khis0085.xml Description: Brackets and parentheses in epigraphic text
 khis0085.xml Description: Brackets and parentheses in epigraphic text
 kzik0001.xml Description: Brackets and parentheses in epigraphic text
 kzik0001.xml Description: Brackets and parentheses in epigraphic text
 mger0059.xml Description: Brackets and parentheses in epigraphic text
 mger0059.xml Description: Brackets and parentheses in epigraphic text
 mums0003.xml Description: Angle brackets in epigraphic text
 mums0003.xml Description: Angle brackets in epigraphic text
 mums0003.xml Description: Brackets and parentheses in epigraphic text
 mums0003.xml Description: Brackets and parentheses in epigraphic text
 qumr0002.xml Description: Brackets and parentheses in epigraphic text
 qumr0002.xml Description: Brackets and parentheses in epigraphic text
 rafi0008.xml Description: Brackets and parentheses in epigraphic text
 rafi0008.xml Description: Brackets and parentheses in epigraphic text
 rams0003.xml Description: Brackets and parentheses in epigraphic text
 rams0003.xml Description: Brackets and parentheses in epigraphic text
 rams0004.xml Description: Angle brackets in epigraphic text
 rams0004.xml Description: Angle brackets in epigraphic text
 sepp0018.xml Description: Angle brackets in epigraphic text
 sepp0018.xml Description: Angle brackets in epigraphic text
 sepp0020.xml Description: Angle brackets in epigraphic text
 sepp0020.xml Description: Angle brackets in epigraphic text
 shap0004.xml Description: Brackets and parentheses in epigraphic text
 shap0004.xml Description: Brackets and parentheses in epigraphic text
 squf0003.xml Description: Brackets and parentheses in epigraphic text
 squf0003.xml Description: Brackets and parentheses in epigraphic text
 suke0001.xml Description: Brackets and parentheses in epigraphic text
 suke0001.xml Description: Brackets and parentheses in epigraphic text
 tala0004.xml Description: Angle brackets in epigraphic text
 tala0004.xml Description: Angle brackets in epigraphic text
 tibe0004.xml Description: Brackets and parentheses in epigraphic text
 tibe0004.xml Description: Brackets and parentheses in epigraphic text
 zoor0136.xml Description: Angle brackets in epigraphic text
 zoor0136.xml Description: Angle brackets in epigraphic text
rafi0008.xml Description: Angle brackets in epigraphic text
rafi0008.xml Description: Angle brackets in epigraphic text

**Comment by GaiaLembi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Angle brackets and other characters in epigraphic texts](https://trello.com/c/la5MKa4t/50-angle-brackets-and-other-characters-in-epigraphic-texts)

**Comment by emylonas** [comment]
em do quick check

**Comment by GaiaLembi** [comment]
All done. As for bshe0014 I marked the parenthesis in diplomatic as AM, and corrected a bunch of other stuff in both diplomatic and edited transcription
