### ISSUE TITLE
some inscriptions already have a period as text

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#70]
Attribute "period" was already specified for element "date".
jeru0369.xml   http://n2t.net/ark:/99152/p0m63nj3bbf      Second Temple Period
jeru0370.xml   http://n2t.net/ark:/99152/p0m63nj3bbf       Persian
jeru0371.xml   http://n2t.net/ark:/99152/p0m63nj3bbf       Persian
jeru0372.xml    http://n2t.net/ark:/99152/p0m63njw6r7      Persian
jeru0373.xml   http://n2t.net/ark:/99152/p0m63njw6r7      Persian
jeru0374.xml    http://n2t.net/ark:/99152/p0m63njw6r7      Persian
jeru0375.xml    http://n2t.net/ark:/99152/p0m63njgvtd       Hellenistic
jeru0376.xml    http://n2t.net/ark:/99152/p0m63nj3bbf      Persian
jeru0377.xml     http://n2t.net/ark:/99152/p0m63njgvtd     http://n2t.net/ark:/99152/p0m63njbxb9 Hellenistic
jeru0379.xml     http://n2t.net/ark:/99152/p0m63njgvtd    http://n2t.net/ark:/99152/p0m63njbxb9 Hasmonean
jeru0380.xml     http://n2t.net/ark:/99152/p0m63njgvtd    http://n2t.net/ark:/99152/p0m63njbxb9 Hasmonean, Herodian
jeru0381.xml     http://n2t.net/ark:/99152/p0m63njw2xp    Early Roman
jeru0382.xml     http://n2t.net/ark:/99152/p0m63njbxb9    Early Roman
jeru0393.xml     http://n2t.net/ark:/99152/p0m63njtk9m     http://n2t.net/ark:/99152/p0m63njjcn4    Talmudic
jeru0490.xml   http://n2t.net/ark:/99152/p0m63njgvtd    http://n2t.net/ark:/99152/p0m63njbxb9 
   Herodian

**Comment by emylonas** [comment]
Also, some of these are inconsistent

**Comment by GaiaLembi** [comment]
Elli, I do not know where the text within the PeriodO box came from: I did not put them in and I am going to cancel them.
The links as I put them into the spreadsheet are correct.
