### ISSUE TITLE
ahmadiyye has two Pleiades values

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#73]
Hi Gaia  - Ahma0001 has this Pleiades URL: https://pleiades.stoa.org/places/678006
and Ahma0002, 0003 have this one : http://pleiades.stoa.org/places/254380758

The first one ( https://pleiades.stoa.org/places/678006 ) seems correct, and takes you to the Pleiades page for Ahmadiyye. The second one ( http://pleiades.stoa.org/places/254380758 ) doesn't seem to work at all and asks for a login page in Pleiades.

Can you check the first one and if it's correct, then change the other two?

**Comment by GaiaLembi** [comment]
Done. The first one was indeed the correct one
