### ISSUE TITLE
Aramaic/Hebrew words written in Greek characters (e.g. beth0023)

### ISSUE THREAD

**Issue by GaiaLembi** [Brown-University-Library/iip-texts#74]
1) Find in how many inscriptions this is happening;
2) Mark the transcription _and not the translation_ accordingly.

**Comment by emylonas** [comment]
beth0231.xml:
 <rs type="religTitle" ana="interpretations.xml#rabbi"><?iip-script greek?>Rabbi </rs>

<persName xml:lang="hbo " ref="persons.xml#beth0231p02"><?iip-script greek?>Gamaliel</persName>.</p>

beth0232.xml:
...ersName>'s (tomb). Of <rs type="religTitle" ana="interpretations.xml#rabbi"><?iip-script greek?>Rabbi </rs>

<persName xml:lang="hbo " ref="persons.xml#beth0232p02"><?iip-script greek?>Anianos </persName> the <rs type="epithet" ana="interpreta...

 ...Anianos </persName> the <rs type="epithet" ana="interpretations.xml#little"><?iip-script greek?>Little </rs> (lit: the dwarf)</p>

beth0119.xml  I think this is hebrew/aramaic with greek letters.

**Comment by emylonas** [comment]
Discussed with @zeichman  - these aren't transliterated Hebrew/Greek or one language written in an alphabet not normally associated with that language. These are phrases in Greek, repeating what was said in the Hebrew. Same with the Hebrew phrase repeating the Greek above it. Removed the `<?iip-script greek?>` type elements from the translations. They are marked correctly in the transcription. Closing
