### ISSUE TITLE
Zotero entry has several IIP-000 tags

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#76]
Magen, Yitzhak; Misgav, Haggai;   Tsfania, Levana, Mount   Gerizim Excavations 2004  Judea & Samaria Publications
has  IIP-715 as Loc in Archive
but has the following tag values:  IIP-711; IIP-714; IIP-715;   IIP-filler-tag

jeru0529 uses IIP-711
nothing uses IIP-714
and 395 Mt  Gerizim inscriptions use  IIP-715

I can change the jerusalem inscription to IIP-715 if you'd like and then we can delete IIP-711 and IIP-714 as tags. 

there are some other duplicate Zotero entries with different tags that we should change, but I'd like to do it together.

**Comment by emylonas** [comment]
Gaia fixed, elli closed

**Comment by GaiaLembi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Zotero issues](https://trello.com/c/fPLKDgSl/58-zotero-issues)
