### ISSUE TITLE
Duplicate books in Zotero

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#77]
**Legions Romaines en Palestine** recommend changing 315 with only 3 files to 268. So fix 268 and then delete 315
IIP-315 
- caes0004 (2)
- caes0005 (2)
- caes0006 (2)

IIP-268
- caes0047 (2)
- caes0045
- caes0051
- caes0119
- caes0146

**Ossuary Inscriptions from the Caiaphas Tomb"
IIP-121 none
IIP-638 9 items jent0001, jent0004 (2), jent0005 (2) ,jent0006 (2), jent0007 (2)
either pick the best one and change its tag to 638, or edit 638 so it's got the best info

**Inscriptiones Latinae Selectae**
Note that the zotero citation type is _document_ which is wrong. 
IIP-216 none
IIP-312 caes0003
same suggestion as above

**Epigraphischer Beitrag** you will have to look at the two entries in the general not the duplicate list, because one is type _journal article_ and one is type _book section_. I'm pretty sure that it's a book section (which is IIP-197...)
IIP-328 caes0043
IIP-197 none

**Interpreting the Theodotus Inscription** 
not referenced at all

**Kanaanäische und aramäische...**
IIP-451, IIP-581 not referenced at all.

**Comment by GaiaLembi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Zotero issues](https://trello.com/c/fPLKDgSl/58-zotero-issues)

**Comment by emylonas** [comment]
done
