### ISSUE TITLE
Bulletin Epigraphique (REG)

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#79]
In this case, I will list all the volumes of REG that are cited, and which IIP number goes along with them. There are 3 duplicates, I'll list inscription numbers in those cases, for each entry so if necessary they can be reconciled. They may not be duplicates, but I wonder how many "Bulletin Epigraphiques" would be in each issue... 

v. 50 IIP-529
v. 62 IIP-531
v. 68 IIP-340
v. 69 IIP-426

_DUPLICATE
v. 71 IIP-341 p. 169-363 caes0109
v. 71 IIP-526 beth0184, beth0186, beth0189, beth0190, beth0192_

v. 72 IIP-401
v. 73 IIP-343
v. 74 IIP-344
v. 75 IIP-345
v. 76 IIP-346

_DUPLICATE
v. 77 IIP-528 beth0201
v. 77 IIP-347 p. 127-259 caes0080, caes0133_

v. 78 IIP-348
v. 79 IIP-349

_DUPLICATE
v. 80 IIP-320 p. 453-573 (also some odd numbers in the issue field) caes0064
v. 80 IIP-350 caes0041, caes0125, caes0126, caes0139, caes0167, caes0181, caes0185, caes0245, caes0246, caes0315_

v. 90 IIP-352
v. 91 IIP-321
v. 92 IIP-354

v. 71

**Comment by GaiaLembi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Zotero issues](https://trello.com/c/fPLKDgSl/58-zotero-issues)

**Comment by GaiaLembi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Zotero issues](https://trello.com/c/fPLKDgSl/58-zotero-issues)

**Comment by emylonas** [comment]
done
