### ISSUE TITLE
strange characters

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#98]
`\ _ ʾ " ̔ ˊ & $ ‘ 𐅹 * ´ ̒ ­ # | ʹ ͂ ' ? ̢ ’`

NOTE these are the correct Greek number signs:   `͵` at the left or `ʹ` on the right of the number

**TO FIX**
`\` [2 in jord0001]
` _` [beth0242, idum516]
`$ and #` [jeru0307]
`&` [entity ref. 4 in jord0001 and 3 in caes0111 ] 
`?` [ beth0206, 3 in beth0215, beth0216, beth0217, bshe0112, 44 in jord0001, caes0044, hamm0008, hamm0012, hamm0013, sena0001, sena0002, sena0003, fiqg0016, 2 in mari0004, mari0005, mger0296]
'*' [mare0800, bshe0029, bshe0131]
`"` double quote in zoor0022: μηνὸς" Ἀρτε<lb/>μισίου
`'` apostrophe 35 of them.

NOT AN ERROR
`𐅹` Greek year sign correctly being used in kede0002 

**I've fixed the ones below**
'ˊ' (acute accent) is being used as a number sign in bshe0004. Changed to correct character and tagged as `<num>` (FIXED)
`ʹ` indicated numbers, EM added `<num>` and changed to correct number sign (see below) (FIXED)
'‘' left single quote used as rough breathing tdor0003 corrected to a rough breathing character. Also fixed the `<lb break="no"/>` to `Ῥοῦ<lb/>γεῦσαι ` (Ῥου is a word). (FIXED)

...not done

**Comment by zeichman** [comment]
I have gone through and checked each of these. All of these were fixed during our wordlist read-throughs and corrections.
